NDEV-532 json logger for proxy and neon-cli
neonevm/proxy-model.py pull request #1046
Opened 2022-12-28 08:36 UTC by gigimon

2023-01-16 21:17 UTC, afalaleev requested changes
Please fix small problems

2023-01-16 21:17 UTC, afalaleev commented on proxy/common_neon/solana_tx_error_parser.py
> +        LOG.error = '. '.join([log for log in log_list if self._is_program_log(log)])
This is an internal parameter of the exception.

2023-01-16 21:17 UTC, afalaleev commented on proxy/common_neon/solana_tx_error_parser.py
> +        if not len(LOG.error):
the same

2023-01-16 21:17 UTC, afalaleev commented on proxy/common_neon/solana_tx_error_parser.py
> +        super().__init__(LOG.error)
the same

2023-01-16 21:17 UTC, afalaleev commented on proxy/testing/test_get_block_hash.py
> -    def test_get_fake_block_by_hash(self):
why do you remove this test?

2023-01-17 11:06 UTC, gigimon commented on proxy/testing/test_get_block_hash.py
> -    def test_get_fake_block_by_hash(self):
return it (can't remember)

2023-01-17 11:57 UTC, afalaleev approved these changes, later dismissed
Please describe the final result in the commit comment, when you squash the commit.
Don't leave the squashed comments from all included commits.

2023-01-20 12:20 UTC, afalaleev approved these changes

2023-01-20 12:27 UTC, merged