122 estimate gas on deploy a contract
neonevm/proxy-model.py pull request #123
Opened 2021-07-16 07:34 UTC by vasiliy-zaznobin

If a param 'to' is empty the value "0x0000000000000000000000000000000…

2021-07-16 11:25 UTC, s-medvedev reviewed
Let implement a special deploy mode for the emulator and get value from it.

2021-08-02 11:08 UTC, anton-lisanin commented
- Revert all changes in the CI files
- Revert all unrelated whitespaces

2021-08-02 11:26 UTC, anton-lisanin requested changes

2021-08-02 11:26 UTC, anton-lisanin commented on proxy/plugin/solana_rest_api.py
> +            debug = param['debug'] if 'debug' in param else ""
There is no `debug` in the param.
Read about RPC parameters here  https://eth.wiki/json-rpc/API#eth_estimategas

2021-08-02 11:26 UTC, anton-lisanin commented on proxy/plugin/solana_rest_api.py
> +            debug = param['debug'] if 'debug' in param else ""
Also `param` may contain a `gas` value and you must return `"0x"` if the estimated gas is more then gas limit specified by the user.

2021-08-02 11:26 UTC, anton-lisanin commented on proxy/plugin/solana_rest_api_tools.py
> +        cmd = 'neon-cli -v -v -v -v --url {} {}'.format(solana_url, arguments)
Revert all code related to `-v` or `debug` in context of emulator

2021-08-02 11:36 UTC, anton-lisanin commented on proxy/plugin/solana_rest_api.py
> +            caller_id = param['from']
`from` may not present in the `param`
Default to 0x00..0

2021-08-02 11:39 UTC, anton-lisanin commented on proxy/plugin/solana_rest_api.py
> +                raise Exception("Missing data in eth_estimateGas param")
Missing data is fine. You should not throw exceptions in this case

2021-08-02 11:39 UTC, anton-lisanin commented on proxy/plugin/solana_rest_api.py
> +            return 999999999
rethrow an exception instead of returning an arbitrary value

2021-08-02 12:42 UTC, vasiliy-zaznobin commented on proxy/plugin/solana_rest_api_tools.py
> +        cmd = 'neon-cli -v -v -v -v --url {} {}'.format(solana_url, arguments)
Fixed

2021-08-02 12:48 UTC, vasiliy-zaznobin commented on proxy/plugin/solana_rest_api.py
> +            caller_id = param['from']
Fixed

2021-08-02 12:48 UTC, vasiliy-zaznobin commented on proxy/plugin/solana_rest_api.py
> +            return 999999999
Fixed

2021-08-02 12:51 UTC, vasiliy-zaznobin commented on proxy/plugin/solana_rest_api.py
> +                raise Exception("Missing data in eth_estimateGas param")
Fixed

2021-08-03 09:04 UTC, anton-lisanin commented
Estimating transaction without data cause an exception

```
2021-08-03 12:03:35,308 - pid:1133 [D] eth_estimateGas:93 - Exception on eth_estimateGas: Command 'neon-cli --url http://localhost:8899 emulate --commitment=recent  --evm_loader B42Fjhhn4xCSapJqnBfdTgM6XLtGiSgbrDkABC3WJdto 0xe7d88a8d79f02617a8785ae7f852fa28b23e8feb 0x01b525379e34d68d238f2b4cb0ad5d73195b6fb2  0x15af1d78b58c40000' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/anton/source/proxy-model.py/proxy/plugin/solana_rest_api.py", line 465, in process_request
    response['result'] = method(*request['params'])
  File "/home/anton/source/proxy-model.py/proxy/plugin/solana_rest_api.py", line 90, in eth_estimateGas
    result = call_emulated(contract_id, caller_id, data, value)
  File "/home/anton/source/proxy-model.py/proxy/plugin/solana_rest_api_tools.py", line 276, in call_emulated
    output = emulator(contract_id, caller_id, data, value)
  File "/home/anton/source/proxy-model.py/proxy/plugin/solana_rest_api_tools.py", line 209, in emulator
    return neon_cli().call(cmd)
  File "/home/anton/source/proxy-model.py/proxy/plugin/solana_rest_api_tools.py", line 226, in call
    return subprocess.check_output(cmd, shell=True, universal_newlines=True)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'neon-cli --url http://localhost:8899 emulate --commitment=recent  --evm_loader B42Fjhhn4xCSapJqnBfdTgM6XLtGiSgbrDkABC3WJdto 0xe7d88a8d79f02617a8785ae7f852fa28b23e8feb 0x01b525379e34d68d238f2b4cb0ad5d73195b6fb2  0x15af1d78b58c40000' returned non-zero exit status 1
```

2021-08-04 11:38 UTC, anton-lisanin commented on proxy/plugin/solana_rest_api_tools.py
> +            p = subprocess.run(args, stdout=subprocess.PIPE, timeout=0.1, universal_newlines=True)
You concatenating arguments into command string then splitting this string to arguments. Why?
Something like this will be mush easier
```python
def call(self, *args):
    try:
        cmd = ["neon-cli", "--commitment=recent", "--evm_loader={}".format(evm_loader_id)] + list(args)
        return subprocess.check_output(cmd, timeout=0.1, universal_newlines=True)
    except subprocess.CalledProcessError as err:
        logger.debug("ERR: neon-cli error {}".format(err))
        raise


neon_cli().call("emulate", sender, contract, data, value)
```

2021-08-06 07:47 UTC, vasiliy-zaznobin commented on proxy/plugin/solana_rest_api_tools.py
> +            p = subprocess.run(args, stdout=subprocess.PIPE, timeout=0.1, universal_newlines=True)
the arguments parameter can contain several arguments and in this context their number is not known

2021-08-06 11:17 UTC, anton-lisanin commented on proxy/plugin/solana_rest_api_tools.py
> +            p = subprocess.run(args, stdout=subprocess.PIPE, timeout=0.1, universal_newlines=True)
So what? 
This doesn't prevent you from passing arguments directly to `subprocess` without concatenating and splitting them first

2021-08-06 11:17 UTC, anton-lisanin commented on proxy/plugin/solana_rest_api_tools.py
> +            p = subprocess.run(args, stdout=subprocess.PIPE, timeout=0.1, universal_newlines=True)
Also `--commitment=` and `--evm_loader=` should be the same in all calls

2021-08-06 16:48 UTC, vasiliy-zaznobin commented on proxy/plugin/solana_rest_api_tools.py
> +            p = subprocess.run(args, stdout=subprocess.PIPE, timeout=0.1, universal_newlines=True)
Fixed

2021-08-09 03:49 UTC, anton-lisanin approved these changes

2021-08-09 03:50 UTC, merged