#291 Proxy refactoring
neonevm/proxy-model.py pull request #324
Opened 2021-11-23 20:04 UTC by otselnik

2021-11-24 09:35 UTC, rozhkovdmitrii requested changes

2021-11-24 09:35 UTC, rozhkovdmitrii commented on proxy/plugin/solana_rest_api_tools.py
> +from proxy.environment import read_elf_params, TIMEOUT_TO_RELOAD_NEON_CONFIG, NEW_USER_AIRDROP_AMOUNT
Our proxy is a module by its definition so we cant use absolute paths to relate the parts, only relative

```python 
from ..environment import read_elf_params, TIMEOUT_TO_RELOAD_NEON_CONFIG, NEW_USER_AIRDROP_AMOUNT
```

2021-11-24 09:35 UTC, rozhkovdmitrii commented on proxy/plugin/solana_rest_api_tools.py
> +        if NEW_USER_AIRDROP_AMOUNT:
Oh, it's not just a moving the code )
It should've been created anyway even if NEW_USER_AMOUNT didn't. We already polished this one before.
Rollback this changes please

2021-11-24 09:35 UTC, rozhkovdmitrii commented on proxy/common_neon/address.py
> +from proxy.environment import neon_cli, ETH_TOKEN_MINT_ID, EVM_LOADER_ID
I understand it works fine but relative paths should be

2021-11-24 09:35 UTC, rozhkovdmitrii commented on proxy/common_neon/emulator_interactor.py
> +from proxy.environment import neon_cli
I understand it works fine but relative paths should be

2021-11-24 09:35 UTC, rozhkovdmitrii commented on proxy/common_neon/neon_instruction.py
> +    def trx_with_create_and_airdrop(self, eth_account, code_acc=None) -> Transaction:
`make_trx_with_create_and_airdrop` like the other methods in this class

2021-11-24 09:35 UTC, rozhkovdmitrii commented on proxy/common_neon/neon_instruction.py
> +from proxy.environment import EVM_LOADER_ID, ETH_TOKEN_MINT_ID , COLLATERAL_POOL_BASE, NEW_USER_AIRDROP_AMOUNT
I understand it works fine but relative paths should be

2021-11-24 09:35 UTC, rozhkovdmitrii commented on proxy/common_neon/solana_interactor.py
> +from proxy.environment import EVM_LOADER_ID, CONFIRMATION_CHECK_DELAY
I understand it works fine but relative paths should be

2021-11-24 09:35 UTC, rozhkovdmitrii commented on proxy/common_neon/transaction_sender.py
> +from proxy.plugin.eth_proto import Trx as EthTrx
I understand it works fine but relative paths should be

2021-11-24 09:35 UTC, rozhkovdmitrii commented on proxy/indexer/solana_receipts_update.py
> +from proxy.environment import SOLANA_URL, EVM_LOADER_ID
relative paths

2021-11-24 09:35 UTC, rozhkovdmitrii commented on proxy/indexer/utils.py
> +from proxy.environment import SOLANA_URL, EVM_LOADER_ID, ETH_TOKEN_MINT_ID
Relative paths

2021-11-24 09:35 UTC, rozhkovdmitrii commented on proxy/plugin/solana_rest_api.py
> +from proxy.indexer.utils import get_trx_results, LogDB
relative paths

2021-11-25 12:30 UTC, rozhkovdmitrii approved these changes

2021-11-25 12:30 UTC, rozhkovdmitrii commented on proxy/common_neon/neon_instruction.py
> +    def create_collateral_pool_address(self, collateral_pool_index):
@staticmethod

2021-11-25 12:30 UTC, rozhkovdmitrii commented on proxy/common_neon/address.py
> +def accountWithSeed(base, seed, program=PublicKey(EVM_LOADER_ID)):
`program` redundant

2021-11-25 12:30 UTC, rozhkovdmitrii commented on proxy/common_neon/address.py
> +    logger.debug('accountWithSeed %s', str(result))
logging here redundant

2021-11-25 12:30 UTC, rozhkovdmitrii commented on proxy/common_neon/neon_instruction.py
> +    def make_create_eth_account_trx(self, eth_address, code_acc=None):
Original definition is:

```python
def make_create_eth_account_trx(signer: SolanaAccount, eth_address: EthereumAddress, evm_loader_id, code_acc=None) \
                                -> Tuple[Transaction, PublicKey]:
```

2021-11-25 12:30 UTC, rozhkovdmitrii commented on proxy/common_neon/neon_instruction.py
> +        self.operator = operator
`self.operator_pda_account: SolanaAccount = operator_pda_account`

2021-11-25 12:30 UTC, rozhkovdmitrii commented on proxy/common_neon/neon_instruction.py
> +        self.operator_token = getTokenAddr(self.operator)
`operator_associated_token_address: PulicKey = ...`

2021-11-25 12:30 UTC, rozhkovdmitrii commented on proxy/common_neon/neon_instruction.py
> +        owner_associated_token_account = getTokenAddr(self.operator)
Already have `operator_token` )

2021-11-25 12:30 UTC, rozhkovdmitrii commented on proxy/common_neon/transaction_sender.py
> +                address = bytes.fromhex(acc_desc["address"][2:])
It was dropped from `develop` branch before

2021-11-25 13:26 UTC, rozhkovdmitrii approved these changes, later dismissed

2021-11-25 13:26 UTC, rozhkovdmitrii commented on proxy/common_neon/solana_interactor.py
> +        #return resp
was removed from develop before

2021-11-25 13:26 UTC, rozhkovdmitrii commented on proxy/common_neon/solana_interactor.py
> +        #if not resp["result"]:
was removed from here before

2021-11-25 13:26 UTC, rozhkovdmitrii commented on proxy/common_neon/solana_interactor.py
> +    #            logger.debug('Confirmed transaction:', resp)
was removed from here before

2021-11-25 13:26 UTC, rozhkovdmitrii commented on proxy/common_neon/transaction_sender.py
> +                return signature
The same as `return  check_if_continue_returned(result)`?

In other case you should check it like that:

```
if signature is not None:
```
and return None explicitly

2021-11-25 17:01 UTC, otselnik commented on proxy/common_neon/neon_instruction.py
> +    def create_collateral_pool_address(self, collateral_pool_index):
fixed

2021-11-26 05:29 UTC, rozhkovdmitrii approved these changes, later dismissed

2021-12-02 11:34 UTC, s-medvedev commented on proxy/common_neon/neon_instruction.py
> +        self.operator_associated_token_address = getTokenAddr(self.operator_pda_account)
I suggest renaming back.
We can talk about PDA (Program Derived Address) account only when it is built this way. For the operator's account, it's not correct, because the operator uses their own Solana account, which can't be PDA. So, this name confuse.
Which information gives `operator_associated_token_address`? I think `operator_neon_balance` will be better in this case.

2021-12-02 11:47 UTC, rozhkovdmitrii commented on proxy/common_neon/neon_instruction.py
> +        self.operator_associated_token_address = getTokenAddr(self.operator_pda_account)
Yeah, you're right! 
I propose instead of `associated_token_address` use `operator_neon_address` here and `neon_address` everywhere it is needed.

2021-12-02 11:55 UTC, otselnik commented on proxy/common_neon/neon_instruction.py
> +        self.operator_associated_token_address = getTokenAddr(self.operator_pda_account)
So, what in the end?
`operator_associated_token_address` -> `operator_neon_balance`
`associated_token_address` -> `neon_address` or `neon_balance`?

2021-12-02 11:58 UTC, rozhkovdmitrii commented on proxy/common_neon/neon_instruction.py
> +        self.operator_associated_token_address = getTokenAddr(self.operator_pda_account)
`operator_neon_address` i think. `getTokenAddr` actually doesn't  return a balance )

2021-12-02 12:16 UTC, s-medvedev commented on proxy/common_neon/neon_instruction.py
> +        self.operator_associated_token_address = getTokenAddr(self.operator_pda_account)
Let's stop on `operator_neon_address`

2021-12-02 13:47 UTC, s-medvedev approved these changes

2021-12-02 13:47 UTC, merged