330 create airdropper service
neonevm/proxy-model.py pull request #331
Opened 2021-11-26 16:46 UTC by ivandzen

2021-11-29 20:51 UTC, otselnik requested changes

2021-11-29 20:51 UTC, otselnik commented on proxy/indexer/solana_receipts_update.py
> +    airdrop_amount = os.environ.get('AIRDROP_AMOUNT', 0)
If you are running this util from the command line, wouldn't it be better to pass them parameters instead of getting them from the environment?

2021-11-29 20:51 UTC, otselnik commented on proxy/indexer/solana_receipts_update.py
> -from proxy.environment import solana_url, evm_loader_id
What's wrong with getting `solana_url` and `evm_loader_id` from the environment module?

2021-11-29 20:51 UTC, otselnik commented on proxy/indexer/solana_receipts_update.py
> +    def __init__(self,
I think it is reasonable here to do it through inheritance:
```python
class Gatherer:
  def __init__(self):
        self.client = Client(solana_url)
        self.canceller = Canceller()
        self.logs_db = LogDB()
        self.transaction_receipts = SQLDict(tablename="known_transactions")
        self.constants = SQLDict(tablename="constants")

        self.last_slot = 0
        self.current_slot = 0
        self.transaction_order = []
        if 'last_block' not in self.constants:
            self.constants['last_block'] = 0
        self.counter_ = 0
  
  def run(self):
     pass

  def gather_unknown_transactions(self):
     same

  def get_tx_receipts(self):
     same


class Airdroper(Gatherer):
  def __init__(self):
    Gatherer.__init__(self)
    ...

  def run(self):
      self.gather_unknown_transactions()
      self.process_receipts()

...


class Indexer(Gatherer):
  def __init__(self):
    Gatherer.__init__(self)
    ...

  same

```

2021-11-29 20:51 UTC, otselnik commented on proxy/indexer/solana_receipts_update.py
> +    def run(self):
In `airdropper` mode `gather_blocks` and `canceller.unlock_accounts` are excessive here.

2021-11-29 20:51 UTC, otselnik commented on proxy/indexer/solana_receipts_update.py
> +                    if self.airdropper_mode:
airdropper_mode makes 95% of this function excessive. 
It is better to have for process_trx_airdropper_mode own process_receipts function:
```python
    def process_receipts(self):
        for signature in self.transaction_order:
            if signature in self.transaction_receipts:
                trx = self.transaction_receipts[signature]
                if trx is None:
                    logger.error("trx is None")
                    del self.transaction_receipts[signature]
                    continue
                if trx['transaction']['message']['instructions'] is not None:
                    if self.airdropper_mode:
                        self.process_trx_airdropper_mode(trx, signature)
```
Or to move another part in function, somehow like:
```python
if ardrop_mode:
  self.process_trx_airdropper_mode(trx, signature)
else:
  self.process_trx_indexermode(trx, signature)
```

2021-12-01 11:40 UTC, ivandzen commented
It is decided to make changes in sope of epic: https://github.com/neonlabsorg/proxy-model.py/issues/335

2021-12-01 11:40 UTC, closed without merging