#425 use Solana's block height as neon block number
neonevm/proxy-model.py pull request #426
Opened 2021-12-30 16:09 UTC by otselnik

2022-01-03 09:42 UTC, ivandzen requested changes

2022-01-03 09:42 UTC, ivandzen commented on proxy/indexer/indexer_db.py
> +        block_hash, block_number, _ = self.get_block_info(client, slot)
'return None' case not handled

2022-01-03 09:42 UTC, ivandzen commented on proxy/indexer/indexer.py
> +                logger.debug(f"FAILED {max_height} {max_slot} {last_block}")
logger.warning/error is better to be used here

2022-01-03 09:42 UTC, ivandzen commented on proxy/indexer/indexer_db.py
> +        block = self.blocks.get(slot, None)
I don't see where data stored to this container. Seems it will always be empty

2022-01-05 10:26 UTC, ivandzen commented on proxy/indexer/indexer_db.py
> +        block = self.blocks.get(slot, None)
Added fix (see below line 87)

2022-01-05 10:27 UTC, ivandzen commented on proxy/indexer/indexer_db.py
> +        block_hash, block_number, _ = self.get_block_info(client, slot)
Fix added

2022-01-05 10:27 UTC, ivandzen commented on proxy/indexer/indexer.py
> +                logger.debug(f"FAILED {max_height} {max_slot} {last_block}")
Fix added

2022-01-05 11:01 UTC, ivandzen commented
Suggest to add some tests

2022-01-05 11:57 UTC, afalaleev requested changes

2022-01-05 11:57 UTC, afalaleev commented on proxy/plugin/solana_rest_api.py
> +        slot = self.db.get_slot_by_number(block_number)
_eth_getBlockByNumber('latest')_ on a live Solana cluster (testnet/mainnet/devnet) will return many errors.
Reasons:
- _process_block_tag('latest')_ returns the last block on the Solana node
- _db.get_slot_by_number(height)_ returns the last block in the DB

So, if block doesn't exist in DB,  a clients receive error _"Not found block by number latest"_

2022-01-05 16:33 UTC, afalaleev requested changes

2022-01-05 16:33 UTC, afalaleev commented on proxy/indexer/indexer.py
> +        confirmed_blocks = self.client.get_confirmed_blocks(last_block_slot)["result"]
_get_confirmed_blocks()_ is deprecated method.
And it returns only 500'000 blocks.

2022-01-15 10:11 UTC, afalaleev approved these changes

2022-01-15 10:12 UTC, merged