322 check try except block for right logging
neonevm/proxy-model.py pull request #467
Opened 2022-01-20 09:59 UTC by vasiliy-zaznobin

2022-01-20 10:10 UTC, afalaleev requested changes

2022-01-20 10:10 UTC, afalaleev commented on proxy/indexer/indexer.py
> +            self.warning(f'storage {storage_account}, tx.neon_tx({tx.neon_tx}) != neon_tx({neon_tx})')
self._log_warning adds information about the current parsed instruction:
https://github.com/neonlabsorg/proxy-model.py/pull/467/files#diff-11de75dcede9b24f514596cfdb04fa1c34c8da38f06ac74f93bfc012076783cbL260

2022-01-20 10:10 UTC, afalaleev commented on proxy/indexer/indexer.py
> +            self.warning(f'storage {storage_account}, tx.neon_tx({tx.neon_tx}) != neon_tx({neon_tx})')
https://github.com/neonlabsorg/proxy-model.py/pull/467/files#diff-11de75dcede9b24f514596cfdb04fa1c34c8da38f06ac74f93bfc012076783cbL282

{self} -> is replaced with self.__str__()

2022-01-20 11:16 UTC, vasiliy-zaznobin commented on proxy/indexer/indexer.py
> +            self.warning(f'storage {storage_account}, tx.neon_tx({tx.neon_tx}) != neon_tx({neon_tx})')
Added current parsed instruction in the log string

2022-01-20 12:53 UTC, afalaleev approved these changes, later dismissed

2022-01-21 03:46 UTC, afalaleev commented on proxy/indexer/indexer.py
> +            self.error(f'Neon tx rlp error: {rlp_error}, on instruction: {self}')
The format is changed here.

2022-01-21 06:38 UTC, vasiliy-zaznobin commented on proxy/indexer/indexer.py
> +            self.error(f'Neon tx rlp error: {rlp_error}, on instruction: {self}')
Fixed

2022-01-21 14:41 UTC, afalaleev approved these changes

2022-01-21 14:41 UTC, merged