#483 save signature on cancel
neonevm/proxy-model.py pull request #503
Opened 2022-01-27 06:34 UTC by otselnik

2022-01-27 07:44 UTC, afalaleev requested changes
The additional place IterativeNeonTxSender::_on_success_send in transaction_sender.py

2022-01-27 07:44 UTC, afalaleev commented on proxy/indexer/indexer.py
> +        tx.neon_res.sol_sign = self.ix.sign.slot
tx.neon_res.sol_sign = self.ix.sign

2022-01-27 20:11 UTC, otselnik commented on proxy/indexer/indexer.py
> +        tx.neon_res.sol_sign = self.ix.sign.slot
fixed

2022-01-28 08:10 UTC, afalaleev commented on proxy/indexer/indexer.py
> -                    tx.neon_res.slot = self.indexed_slot
This was the fix of the 
https://github.com/neonlabsorg/proxy-model.py/issues/477

2022-01-28 09:46 UTC, afalaleev approved these changes

2022-01-28 09:47 UTC, merged