#480 Do not create new read only accounts
neonevm/proxy-model.py pull request #531
Opened 2022-02-01 06:48 UTC by anton-lisanin

2022-02-02 06:34 UTC, afalaleev approved these changes, later dismissed

2022-02-02 10:08 UTC, sinev-valentine approved these changes

2022-02-03 20:51 UTC, sinev-valentine requested changes, later dismissed
proxy.testing.test_erc20_wrapper_contract.Test_erc20_wrapper_contract:

evm_loader fails in line:
https://github.com/neonlabsorg/neon-evm/blob/96bcf0b88fc3293efd3026339a57bdab9f78e6b7/evm_loader/program/src/account_data.rs#L135

2022-02-04 12:28 UTC, s-medvedev approved these changes

2022-02-07 06:56 UTC, merged