490 check operator so ls
neonevm/proxy-model.py pull request #557
Opened 2022-02-08 17:24 UTC by vasiliy-zaznobin

If the balance value of one of the operator's accounts has become equal to
        the value of the variable MIN_OPERATOR_BALANCE_TO_ERR or less,
        then an error is returned to the client who requested the execution of the transaction
        and an error is written to the log:
```
ERROR:neon.Proxy:Operator account BMp6gEnveANdvSvspESJUrNczuHz1GF5UQKjVLCkAZih has NOT enough SOLs; balance = 7976686866080; min_operator_balance_to_err = 1049000000000000000000000000
```

If the balance value of one of the operator's accounts becomes equal to
        the value of the variable MIN_OPERATOR_BALANCE_TO_WARN or less,
        then a warning is written to the log:
```
WARNING:neon.Proxy:Operator account BMp6gEnveANdvSvspESJUrNczuHz1GF5UQKjVLCkAZih SOLs are running out; balance = [0-9]+; min_operator_balance_to_warn = 1049000000000000000000000000; min_operator_balance_to_err = 1049049000;
```

2022-02-09 05:50 UTC, afalaleev approved these changes

2022-02-09 06:07 UTC, afalaleev requested changes

2022-02-09 06:07 UTC, afalaleev commented on proxy/common_neon/transaction_sender.py
> +        self._validate_operator_balance()
In this place the operator key is already selected and the transaction execution fails as result.
Better to add this validation to https://github.com/neonlabsorg/proxy-model.py/blob/d6ff1e0f8bda95b76776d53886be360ab0a96fe3/proxy/common_neon/transaction_sender.py#L300-L302

As result, the OperatorResourceList will switch to another operator key.
Fail happens only when OperatorResourceList doesn't have operator key with enough SOLs.

2022-02-09 06:59 UTC, vasiliy-zaznobin commented on proxy/common_neon/transaction_sender.py
> +        self._validate_operator_balance()
If it was not possible to select/create a resource, this is a different situation and we do not handle it here.

2022-02-09 12:04 UTC, vasiliy-zaznobin commented on proxy/common_neon/transaction_sender.py
> +        self._validate_operator_balance()
The new behavior has been implemented

2022-02-09 13:55 UTC, afalaleev requested changes

2022-02-09 13:55 UTC, afalaleev commented on proxy/common_neon/transaction_sender.py
> +    def init_resource_info(self, solana: SolanaInteractor) -> OperatorResourceInfo:
This parameter is surplus.
OperatorResourceList already has solana: `self._s.solana`

2022-02-09 13:55 UTC, afalaleev commented on proxy/common_neon/transaction_sender.py
> +                    self.error(f'Operator has NO resources!')
This log record is surplus

All exceptions with tracebacks are printed in this place - https://github.com/neonlabsorg/proxy-model.py/blob/0e9ada600ae723ff6ee9512fafc8fbbadf77dded/proxy/plugin/solana_rest_api.py#L505-L507

2022-02-10 06:28 UTC, vasiliy-zaznobin commented on proxy/common_neon/transaction_sender.py
> +    def init_resource_info(self, solana: SolanaInteractor) -> OperatorResourceInfo:
Fixed

2022-02-10 06:28 UTC, vasiliy-zaznobin commented on proxy/common_neon/transaction_sender.py
> +                    self.error(f'Operator has NO resources!')
Fixed

2022-02-11 03:32 UTC, afalaleev approved these changes

2022-02-11 06:41 UTC, merged