#447 save instruction statistics
neonevm/proxy-model.py pull request #573
Opened 2022-02-13 20:10 UTC by otselnik

2022-02-24 12:53 UTC, otselnik commented
Move step count to solana_neon_transactions
Add heap info

2022-02-25 06:25 UTC, afalaleev approved these changes

2022-03-16 14:54 UTC, rozhkovdmitrii requested changes

2022-03-16 14:54 UTC, rozhkovdmitrii commented on proxy/indexer/accounts_db.py
> +        if not neon_account:
does it pretend to be a separate method?

2022-03-16 14:54 UTC, rozhkovdmitrii commented on proxy/db/scheme.sql
> +        token_income BIGINT
`neon_income`

2022-03-16 14:54 UTC, rozhkovdmitrii commented on proxy/db/scheme.sql
> +        sol_sign CHAR(88),
the first field called same as the table?

`neon_account` - `neon_accounts`

can we rename the key?

2022-03-16 14:54 UTC, rozhkovdmitrii commented on proxy/indexer/accounts_db.py
> +    def set_acc_indexer(self, neon_account: str, pda_account: str, code_account: str, slot: int, sol_sign: str):
```
def set_acc_indexer(self, neon_account: NeonAccount)
```

2022-03-16 14:54 UTC, rozhkovdmitrii commented on proxy/indexer/costs_db.py
> +from ..indexer.utils import CostInfo
```py
from ..indexer.data import CostInfo
```

2022-03-16 14:54 UTC, rozhkovdmitrii commented on proxy/indexer/costs_db.py
> +            rows.append((
is it applicable like that:

`rows.append(*const) ` or `rows.append(**costs)`

2022-03-16 14:54 UTC, rozhkovdmitrii commented on proxy/indexer/costs_db.py
> +                INSERT INTO {self._table_name}
get rid of table_name

2022-03-16 14:54 UTC, rozhkovdmitrii commented on proxy/indexer/utils.py
> +    def __init__(self, sign: str, tx: dict, program: PublicKey):
from typing import Dict
tx: Dict[str, Any]

2022-03-16 14:54 UTC, rozhkovdmitrii commented on proxy/indexer/utils.py
> +            self.setup(tx, program)
setup is bad

`init_from_tx`

2022-03-16 14:54 UTC, rozhkovdmitrii commented on proxy/indexer/utils.py
> +        def heap_log(msg_words: list[str]):
Send me please the example and I'll help you with it

2022-03-16 14:54 UTC, rozhkovdmitrii commented on proxy/indexer/utils.py
> +        def bpf_log(program, msg_words: list[str]):
move it just after the current method

2022-03-16 14:54 UTC, rozhkovdmitrii commented on proxy/indexer/utils.py
> +        for log in tx['meta']['logMessages']:
may be it pretends to be simplified

2022-04-06 07:46 UTC, rozhkovdmitrii requested changes

2022-04-06 07:46 UTC, rozhkovdmitrii commented on proxy/indexer/accounts_db.py
> +    def __init__(self, neon_address: str = None, pda_address: str = None, code_address: str = None, slot: int = 0, code: str = None, sol_sign: str = None):
The constructor is supplied by default by the `@dataclass`. You can easily get rid of it

2022-04-06 07:46 UTC, rozhkovdmitrii commented on proxy/indexer/accounts_db.py
> +    def fill_neon_address_if_missing(self, neon_account: NeonAccountInfo) -> NeonAccountInfo:
def fill_neon_address_if_missing(self, neon_account: NeonAccountInfo) -> bool:

2022-04-06 07:46 UTC, rozhkovdmitrii commented on proxy/indexer/accounts_db.py
> +        if not neon_account.neon_address:
Just use `not None` to check it for `None`

2022-04-06 15:02 UTC, rozhkovdmitrii approved these changes

2022-04-06 17:25 UTC, merged