368 move sql schema to distinct file
neonevm/proxy-model.py pull request #586
Opened 2022-02-18 10:01 UTC by vasiliy-zaznobin

2022-02-21 06:57 UTC, afalaleev requested changes
The main idea wa to move table creation to shell script, which should be executed before proxy/indexer run. 
As result, this script can be executed as part of DB initialization, not as part of proxy/indexer.
And help to resolve issue of trying to create tables by all services - proxy/indexer/airdropper.

In doker-compose file this script should be implemented as separate service (like evm-loader).
And all proxy/indexer/airdropper should start after script complete.

2022-02-23 11:33 UTC, rozhkovdmitrii requested changes

2022-02-23 11:33 UTC, rozhkovdmitrii commented on proxy/__main__.py
> +        print("Will run in db creation mode")
I would bring all this mode related logic into separate paths according to it's belonging.
It might be better to create 

@logged_group("Indexer")
class IndexerApp:
    def run(): ...
...
FaucetApp
DbCreatorApp
ProxyApp

in there to bring all the certain logic into the place it should be

2022-02-23 11:33 UTC, rozhkovdmitrii commented on proxy/__main__.py
> +        print("Will run in db creation mode")
`logger.info()` here and in the other places

2022-02-23 11:33 UTC, rozhkovdmitrii commented on .buildkite/steps/deploy-test.sh
> +    if docker logs dbcreation >dbcreation.log 2>&1; then echo "db creation logs saved"; fi
`... echo "dbcreation logs saved"`

2022-02-23 11:33 UTC, rozhkovdmitrii commented on Dockerfile
> +                                                  postgresql-client-common postgresql-client && \
`postgresql-client` depends on `postgresql-client-common`, that's why it'll be installed automatically

2022-02-23 11:33 UTC, rozhkovdmitrii commented on proxy/db/scheme.py
> +def CREATE_TABLE_OPERATOR_COST() -> Tuple[str, str]:
Function name should be lowercase

2022-02-23 11:33 UTC, rozhkovdmitrii commented on proxy/db/scheme.py
> +    TABLE_NAME_OPERATOR_COST = 'OPERATOR_COST'
Variable in function should be lowercase

2022-02-23 11:33 UTC, rozhkovdmitrii commented on proxy/run-dbcreation.sh
> +python3 -m proxy
```bash
psql -h ${POSTGRES_HOST} -d ${POSTGRES_DB} -U ${POSTGRES_USER} --file=/opt/proxy/db/db_create.sql
```

after that all things will be simple and stupid

2022-02-23 15:07 UTC, vasiliy-zaznobin commented on proxy/__main__.py
> +        print("Will run in db creation mode")
This is redundant at this stage.

2022-02-23 15:19 UTC, vasiliy-zaznobin commented on .buildkite/steps/deploy-test.sh
> +    if docker logs dbcreation >dbcreation.log 2>&1; then echo "db creation logs saved"; fi
fixed

2022-02-23 15:22 UTC, vasiliy-zaznobin commented on proxy/run-dbcreation.sh
> +python3 -m proxy
So far there is no such possibility. Perhaps this will be done in the future. Let's go step by step

2022-02-23 15:28 UTC, vasiliy-zaznobin commented on proxy/__main__.py
> +        print("Will run in db creation mode")
fixed

2022-02-23 15:28 UTC, vasiliy-zaznobin commented on Dockerfile
> +                                                  postgresql-client-common postgresql-client && \
fixed

2022-02-23 15:52 UTC, rozhkovdmitrii commented on proxy/run-dbcreation.sh
> +python3 -m proxy
All you need to do just move `create table`  instructions into the separate `db_create.sql` and get rid of all the extra code from proxy

2022-02-23 16:13 UTC, vasiliy-zaznobin commented on proxy/run-dbcreation.sh
> +python3 -m proxy
Not only. This will also entail reworking the object model.

2022-02-23 16:52 UTC, vasiliy-zaznobin commented on proxy/db/scheme.py
> +    TABLE_NAME_OPERATOR_COST = 'OPERATOR_COST'
fixed

2022-02-23 16:52 UTC, vasiliy-zaznobin commented on proxy/db/scheme.py
> +def CREATE_TABLE_OPERATOR_COST() -> Tuple[str, str]:
fixed

2022-02-24 04:54 UTC, afalaleev requested changes
I agree with @rozhkovdmitrii 
We should remove all table creation from the classes in the proxy.
There are a lot of problems with it.
Postgress doesn't lock the create of table made from different processes.
As a result, if we will execute more than one proxy or proxy and indexer on empty database, one of the processes fails with error that table already exist.

This lock https://github.com/neonlabsorg/proxy-model.py/blob/develop/proxy/indexer/base_db.py#L26 was created to prevent creating of tables within one process. But after splitting of source to 3 different programs (proxy/indexer/airdropper) it doesn't work. There are a lot of fails on starting of the proxy/indexer/airdropper because all of them try to create the same table.

Moving the table creation to separate file will decrease the complex of this procedure and structure of source code. 

I vote to remove of table creation from the source code and create separate file with table structures.
In the future this will allow to add upgrading of the table instead of dropping and creating new tables.

2022-02-25 06:53 UTC, afalaleev submitted a review, later dismissed

2022-02-25 08:43 UTC, rozhkovdmitrii requested changes

2022-02-25 08:43 UTC, rozhkovdmitrii commented on proxy/indexer/sql_dict.py
> +        self._create_table_sql()
Shouldn't we get it out of here?

2022-02-25 08:43 UTC, rozhkovdmitrii commented on proxy/indexer/trx_receipts_storage.py
> +    def create_test_table(self) -> str:
Shouldn't we get it out of here?

2022-02-25 10:42 UTC, vasiliy-zaznobin commented on proxy/indexer/trx_receipts_storage.py
> +    def create_test_table(self) -> str:
No. It is used here: https://github.com/neonlabsorg/proxy-model.py/blob/d02bfee594cfb03b64f3f3584c78fadf17432a57/proxy/testing/test_trx_receipts_storage.py#L12

2022-02-25 10:54 UTC, vasiliy-zaznobin commented on proxy/indexer/sql_dict.py
> +        self._create_table_sql()
No. It is used in airdroper tests

2022-03-12 12:30 UTC, rozhkovdmitrii commented on proxy/docker-compose-test.yml
> +      NEON_ERC20_MAX_AMOUNT: 2000
How does it relate to the issue goal?

2022-03-12 14:26 UTC, otselnik approved these changes

2022-03-12 15:21 UTC, rozhkovdmitrii approved these changes

2022-03-12 15:21 UTC, merged