307 implement withdraw instruction
neonevm/proxy-model.py pull request #591
Opened 2022-02-21 17:19 UTC by ivandzen

2022-03-09 15:24 UTC, gigimon requested changes
We need a cases like:
1. Withdrawal more than exist in account
2. withdraw all balance (if we can't pay for gas)

2022-03-09 15:24 UTC, gigimon commented on Dockerfile
> +ARG EVM_LOADER_REVISION=ci-308-account_v2
change this before merge

2022-03-09 15:24 UTC, gigimon commented on proxy/testing/test_neon_token.py
> +proxy_url = os.environ.get('PROXY_URL', 'http://127.0.0.1:9090/solana')
this's constants must be in uppercase

2022-03-09 15:24 UTC, gigimon commented on proxy/testing/test_neon_token.py
> +        dest_acc = SolanaAccount()
We can move 
```python
dest_acc = SolanaAccount()
solana.request_airdrop(dest_acc.public_key(), 1000_000_000_000)
```
to setup method
https://docs.python.org/3/library/unittest.html#unittest.TestCase.setUp

2022-03-10 10:12 UTC, ivandzen commented on Dockerfile
> +ARG EVM_LOADER_REVISION=ci-308-account_v2
Fix

2022-03-10 10:12 UTC, ivandzen commented on proxy/testing/test_neon_token.py
> +proxy_url = os.environ.get('PROXY_URL', 'http://127.0.0.1:9090/solana')
Fixed

2022-03-10 10:15 UTC, ivandzen commented on proxy/testing/test_neon_token.py
> +        dest_acc = SolanaAccount()
I've decided to create new accounts for every test

2022-03-11 06:54 UTC, gigimon approved these changes

2022-03-11 06:55 UTC, merged