583 introduce full test suite with terraform
neonevm/proxy-model.py pull request #664
Opened 2022-03-18 13:32 UTC by inkognitotester

Add steps for building infrastructure in to pipeline

2022-03-21 15:01 UTC, rozhkovdmitrii requested changes

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/pipeline.yml
> +#  - label: ":cop::skin-tone-2: deploy check"
That was commented to speed up the build during development (it's the short test suite)

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/pipeline.yml
> +    key: "full_tests"
full_test_suite

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/pipeline.yml
> +    if: *main_if
Wouldn't it better to extract these three steps into the separate pipeline called full_test_suite_pipeline.yml and call it dynamically by the condition?

There is another option to define it as **`group step`**

It can be more expressive way to gather this three steps under the hood than weakly related `main_if`

I mean create infrastructure, full_test_suite and destroy_infrastracture steps

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/pipeline.yml
> +    artifact_paths:
shouldn't `artifact_paths` be presented only once in the step?

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/pipeline.yml
> +    commands:
Too many commands have got here, isn't it better to extract them into a  script

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/pipeline.yml
> +      - PROXY_ADDR=`buildkite-agent meta-data get 'PROXY_IP'`
I suggest to use unified style of calling the commands and putting the result everywhere in this style.
I've met only the `$(...)` before

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/pipeline.yml
> +      - export PROXY_URL="http://$$PROXY_ADDR:9091/solana"
Use please curve braces to put the environment. I ask it for two reasons:

1. It's more expressive way
2. To comply the unified style

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/pipeline.yml
> +      - echo $$PROXY_URL
`echo PROXY_URL - $${PROXY_URL}` here and further

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/steps/build-image.sh
> +    --build-arg NEON_EVM_COMMIT=${NEON_EVM_COMMIT} \
Look if the `EVM_LOADER_REVISION` is mentioned in other places

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/steps/tf/build.sh
> +#!/bin/bash
I suggest the following structure:

```
.buildkite
       -full_test_suite
           full-test-suite.sh
           terraform-build.sh | tf-build.sh
           terraform-cleanup.sh
           ...
```

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/steps/tf/build.sh
> +terraform init $TF_BACKEND_CONFIG
curve braces

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/steps/tf/build.sh
> +export TF_VAR_branch=$BUILDKITE_BRANCH
curve braces

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/steps/tf/build.sh
> +export TFSTATE_KEY="tests/test-$BUILDKITE_COMMIT"
.

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/steps/tf/build.sh
> +buildkite-agent meta-data get "PROXY_IP"
Can you please make it more informative? If it's a trace message it should be prepended with what it means


```
Proxy and other services deployed at IP address: 192.168.0.1
Solana deployed at IP address: 192.168.0.2
```

or 

```
PROXY_IP: 192.168.0.1
SOLANA_IP: 192.168.0.2
```

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/steps/tf/build.sh
> +buildkite-agent meta-data get "SOLANA_IP"
the same and fix it please further

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/pipeline.yml
>    - wait
shouldn't it be prepended with a space

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/steps/tf/build.sh
> +export TF_VAR_neon_evm_revision=latest
`latest` or `NEON_EVM_COMMIT` 


have a look at `play-around-buildkite` branch in `neon-evm` repository

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/steps/tf/build.sh
> +export TF_VAR_proxy_model_revision=latest
`latest` or `${BUILDKITE_COMMIT}`

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/steps/tf/destroy.sh
> +ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts
Just wonder to know if it needs to check the exit code.

```
cmd1 && cmd2 && cmd3 # don't know it is the best way
if [ "$?" -ne 0 ]; then   
   echo "Your command exited with non-zero status $result";
   exit 1;
fi
```

## OR

```sh
set -euo pipefail
```

at beginning

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/steps/tf/main.tf
> +  ingress {
space

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/steps/tf/terraform.auto.tfvars
> +#branch               = "develop"
get rid of comments

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/steps/tf/terraform.auto.tfvars
> +neon_evm_revision    = "latest"
`latest` ?

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/steps/tf/terraform.auto.tfvars
> +proxy_model_revision = "latest"
.

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/steps/tf/proxy_init.sh
> +    #image: neonlabsorg/evm_loader:\$\{EVM_LOADER_REVISION:-latest\}
get rid of comments

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/steps/tf/proxy_init.sh
> +    command: bash -c "create-test-accounts.sh 1 && deploy-evm.sh && /opt/spl-token create-account HPsV9Deocecw3GeZv1FkAPNCBRfuVyfw9MMwjwRe1xaU && /opt/spl-token mint HPsV9Deocecw3GeZv1FkAPNCBRfuVyfw9
Isn't it better to bring it into the script

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/steps/tf/proxy_init.sh
> +    depends_on: []
Useless?

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/steps/tf/proxy_init.sh
> +cat > docker-compose-test.override.yml <<EOF
space after <<

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/steps/tf/main.tf
> +    revision  = "latest"
.

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/steps/tf/main.tf
> +  prefix      = "test-stand-solana-"
should it be used [`BUILDKITE_BUILD_NUMBER`](https://buildkite.com/docs/pipelines/environment-variables#bk-env-vars-buildkite-build-number)

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/steps/tf/main.tf
> +
extra space

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/steps/tf/main.tf
> +
.

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/steps/tf/main.tf
> +  prefix      = "test-stand-solana-"
1. `test-stand-solana-` -> `test-stand-proxy-`

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/steps/tf/main.tf
> +  name        = random_id.test-stand-solana.hex
Don't use the random id

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/steps/tf/main.tf
> +  name        = random_id.test-stand-proxy.hex
.

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/steps/tf/main.tf
> +  depends_on = [
.

2022-03-21 15:01 UTC, rozhkovdmitrii commented on .buildkite/steps/tf/proxy_init.sh
> +      - 3334:3333
I just ask my self if it really needs to override default port

2022-03-21 15:01 UTC, rozhkovdmitrii commented on Dockerfile
> +ARG EVM_LOADER_REVISION=latest
`NEON_EVM_COMMIT` ?

2022-03-21 15:01 UTC, rozhkovdmitrii commented on docker-compose/docker-compose-full-test-suite.yml
> +      - NETWORK_NAME=night-stand
```
      - NETWORK_NAME=${NETWORK_NAME}
      - PROXY_URL=${PROXY_URL}
      - NETWORK_ID=${NETWORK_ID}
      - REQUEST_AMOUNT=${REQUEST_AMOUNT}
      - FAUCET_URL=${FAUCET_URL}
      - USE_FAUCET=${USE_FAUCET}
      - SOLANA_URL=${SOLANA_URL}
      - USERS_NUMBER=${USERS_NUMBER}
      - JOBS_NUMBER=${JOBS_NUMBER}
```

2022-03-21 15:05 UTC, rozhkovdmitrii requested changes

2022-03-21 15:05 UTC, rozhkovdmitrii commented on .buildkite/steps/tf/build.sh
> +
`set -euo pipefail

2022-03-21 15:05 UTC, rozhkovdmitrii commented on .buildkite/steps/tf/proxy_init.sh
> +
`set -euo pipefail` ?

2022-03-21 15:33 UTC, inkognitotester commented on .buildkite/pipeline.yml
>    - wait
Added

2022-03-21 15:34 UTC, inkognitotester commented on .buildkite/pipeline.yml
> +#  - label: ":cop::skin-tone-2: deploy check"
Uncommented

2022-03-21 15:34 UTC, inkognitotester commented on .buildkite/pipeline.yml
> +    key: "full_tests"
renamed

2022-03-21 15:35 UTC, inkognitotester commented on .buildkite/pipeline.yml
> +    artifact_paths:
United

2022-03-21 15:38 UTC, inkognitotester commented on .buildkite/steps/tf/build.sh
> +terraform init $TF_BACKEND_CONFIG
Wrapped

2022-03-21 15:42 UTC, inkognitotester commented on .buildkite/steps/tf/main.tf
> +  prefix      = "test-stand-solana-"
Renamed

2022-03-21 15:48 UTC, inkognitotester commented on .buildkite/pipeline.yml
> +      - PROXY_ADDR=`buildkite-agent meta-data get 'PROXY_IP'`
It is an argument for buildkite-agent, not environment variable(key name for key-value storage)

2022-03-21 15:50 UTC, inkognitotester commented on .buildkite/steps/tf/main.tf
> +
Removed

2022-03-21 15:50 UTC, inkognitotester commented on .buildkite/steps/tf/main.tf
> +
Removed

2022-03-21 15:50 UTC, inkognitotester commented on .buildkite/steps/tf/main.tf
> +  ingress {
Removed

2022-03-21 15:52 UTC, inkognitotester commented on .buildkite/steps/tf/main.tf
> +  depends_on = [
Added

2022-03-21 15:53 UTC, inkognitotester commented on .buildkite/steps/tf/proxy_init.sh
> +cat > docker-compose-test.override.yml <<EOF
Removed

2022-03-21 15:54 UTC, inkognitotester commented on .buildkite/steps/tf/proxy_init.sh
> +    #image: neonlabsorg/evm_loader:\$\{EVM_LOADER_REVISION:-latest\}
Done

2022-03-21 15:54 UTC, inkognitotester commented on .buildkite/steps/tf/proxy_init.sh
> +    depends_on: []
Yes, removed

2022-03-21 15:56 UTC, inkognitotester commented on .buildkite/steps/tf/proxy_init.sh
> +      - 3334:3333
I think yes, it's clearer this way

2022-03-21 15:56 UTC, inkognitotester commented on .buildkite/steps/tf/terraform.auto.tfvars
> +#branch               = "develop"
Removed

2022-03-22 13:22 UTC, inkognitotester commented on .buildkite/pipeline.yml
> +      - echo $$PROXY_URL
Done

2022-03-22 13:22 UTC, inkognitotester commented on .buildkite/pipeline.yml
> +      - export PROXY_URL="http://$$PROXY_ADDR:9091/solana"
Done

2022-03-22 13:23 UTC, inkognitotester commented on .buildkite/steps/tf/build.sh
> +#!/bin/bash
Done

2022-03-22 13:24 UTC, inkognitotester commented on .buildkite/steps/tf/build.sh
> +
Added

2022-03-22 13:31 UTC, inkognitotester commented on .buildkite/steps/tf/build.sh
> +export TF_VAR_branch=$BUILDKITE_BRANCH
Done

2022-03-22 13:31 UTC, inkognitotester commented on .buildkite/steps/tf/build.sh
> +export TFSTATE_KEY="tests/test-$BUILDKITE_COMMIT"
Done

2022-03-22 13:35 UTC, inkognitotester commented on .buildkite/steps/tf/build.sh
> +export TF_VAR_neon_evm_revision=latest
Done

2022-03-22 13:35 UTC, inkognitotester commented on .buildkite/steps/tf/build.sh
> +export TF_VAR_proxy_model_revision=latest
Done

2022-03-22 13:36 UTC, inkognitotester commented on .buildkite/steps/tf/build.sh
> +buildkite-agent meta-data get "PROXY_IP"
Removed, used in the other step

2022-03-22 13:36 UTC, inkognitotester commented on .buildkite/steps/tf/build.sh
> +buildkite-agent meta-data get "SOLANA_IP"
Removed, used in the other step

2022-03-22 13:38 UTC, inkognitotester commented on .buildkite/steps/tf/destroy.sh
> +ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts
Added

2022-03-23 06:28 UTC, rozhkovdmitrii commented on .buildkite/pipeline.yml
> +    if: *main_if
won't fix

2022-03-23 06:36 UTC, rozhkovdmitrii commented on .buildkite/steps/build-image.sh
> +    --build-arg NEON_EVM_COMMIT=${NEON_EVM_COMMIT} \
`EVM_LOADER_REVISION` is using in Dockerfile it should be renamed there

2022-03-23 06:41 UTC, rozhkovdmitrii commented on .buildkite/pipeline.yml
> +      - indexer.log
Do those file exist in there?

2022-03-23 10:03 UTC, inkognitotester commented on docker-compose/docker-compose-full-test-suite.yml
> +      - NETWORK_NAME=night-stand
done

2022-03-23 12:14 UTC, rozhkovdmitrii commented on .buildkite/pipeline.yml
> +#        (build.pull_request.base_branch == "develop" && !build.pull_request.draft) ||
Uncoment

2022-03-23 12:54 UTC, rozhkovdmitrii commented on docker-compose/docker-compose-full-test-suite.yml
> +    container_name: ${FTS_CONTAINER_NAME:-full_test_suite}
`${FTS_CONTAINER_NAME:-develop}``

2022-03-24 18:34 UTC, rozhkovdmitrii approved these changes

2022-03-24 18:34 UTC, rozhkovdmitrii commented on .buildkite/pipeline.yml
> -      - "dbcreation.log"
why this has been dropped?

2022-03-24 18:35 UTC, merged