#595 Prometheus Metrics In Proxy Module
neonevm/proxy-model.py pull request #669
Opened 2022-03-23 13:39 UTC by otselnik

2022-03-23 19:38 UTC, gigimon requested changes

2022-03-23 19:38 UTC, gigimon commented on proxy/common_neon/solana_interactor.py
> +    def get_sol_balance_list(self, account_list: List[Union[str, PublicKey]], commitment='confirmed') -> List[int]:
account_list -> accounts_list

2022-03-23 19:38 UTC, gigimon commented on proxy/common_neon/solana_interactor.py
> +            "commitment": commitment
please use only single quotes or only double quotes

2022-03-23 19:38 UTC, gigimon commented on proxy/common_neon/solana_interactor.py
> +        balance_list = []
balances_list

2022-03-23 19:38 UTC, gigimon commented on proxy/plugin/gas_price_calculator.py
> +        if self.sol_price_usd:
decimal better for this

2022-03-23 19:38 UTC, gigimon commented on proxy/plugin/solana_rest_api.py
> +        self.stat_exporter.stat_commit_tx_begin()
If i understand right, this behavior creates additional N+ transactions to Solana for each sendRawTransaction and it's very bad for rpc limits and for speed

2022-03-23 19:38 UTC, gigimon commented on proxy/statistics_exporter/common_metrics.py
> +        """Переместить"""
russian comments

2022-03-23 19:38 UTC, gigimon commented on proxy/statistics_exporter/prometheus_exporter.py
> +            USD_PRISE_NEON, USD_PRISE_SOL, OPERATOR_FEE, GAS_PRICE
USD_PRISE_NEON -> USD_PRICE_NEON

2022-03-23 19:38 UTC, gigimon commented on requirements.txt
> +prometheus_client
pin module version!

2022-03-24 11:02 UTC, otselnik commented on proxy/common_neon/solana_interactor.py
> +    def get_sol_balance_list(self, account_list: List[Union[str, PublicKey]], commitment='confirmed') -> List[int]:
fixed

2022-03-24 11:02 UTC, otselnik commented on proxy/common_neon/solana_interactor.py
> +            "commitment": commitment
Agree. 
Fixed here.
We need some rules for python coding.

2022-03-24 11:02 UTC, otselnik commented on proxy/common_neon/solana_interactor.py
> +        balance_list = []
fixed

2022-03-24 11:02 UTC, otselnik commented on proxy/plugin/gas_price_calculator.py
> +        if self.sol_price_usd:
Fixed

2022-03-24 11:02 UTC, otselnik commented on proxy/plugin/solana_rest_api.py
> +        self.stat_exporter.stat_commit_tx_begin()
Exactly 2 bulk requests are required. The question is how rpc limits take into account bulk requests.

2022-03-24 11:02 UTC, otselnik commented on proxy/statistics_exporter/common_metrics.py
> +        """Переместить"""
Yeah)
Fixed

2022-03-24 11:02 UTC, otselnik commented on proxy/statistics_exporter/prometheus_exporter.py
> +            USD_PRISE_NEON, USD_PRISE_SOL, OPERATOR_FEE, GAS_PRICE
Fixed

2022-03-24 11:02 UTC, otselnik commented on requirements.txt
> +prometheus_client
Fixed

2022-03-24 11:15 UTC, Agronomistech approved these changes

2022-03-24 11:17 UTC, gigimon approved these changes
[@otselnik](https://github.com/otselnik) i set approve for this but disagree with additional calls for balances

2022-03-28 12:08 UTC, afalaleev requested changes
It won't work.
The proxy executes transactions in parallel, so statistics on a live cluster will show strange numbers.
And this is useless, does not provide information about other operators.

2022-03-28 12:10 UTC, afalaleev commented
There is only one way - parse statistics about completed transactions.
In proxy we can accumulate statistics only about connections - number of request of different types, response time and so on.

2022-03-28 12:28 UTC, otselnik commented
@afalaleev 
> There is only one way - parse statistics about completed transactions.

AccountV2 doesn't allow us to get exact operator balance in Noens postfactum. So we won't be able to make any metrics on it in indexer that makes sense.
> does not provide information about other operators.

I think info about other operators must provide their own proxies
> The proxy executes transactions in parallel, so statistics on a live cluster will show strange numbers.

It only shows changes in time and designed to use in monitoring of operators P&L and balances.

2022-04-06 15:08 UTC, afalaleev requested changes

2022-04-06 15:08 UTC, afalaleev commented on proxy/plugin/solana_rest_api.py
> +        if succeed:
An additional `if` 
I think it is better to create two different methods - `_stat_tx_success()`  and `_stat_tx_failed()`

2022-04-06 15:08 UTC, afalaleev commented on proxy/plugin/solana_rest_api.py
> +        self.stat_exporter.stat_commit_request_and_timeout(request.get('method', '---'), resp_time_ms)
Use variable `method` instead of `request.get()`, because  `request = json.loads(request.body)` can fail on parsing json.

2022-04-06 15:08 UTC, afalaleev commented on proxy/plugin/solana_rest_api.py
> +        self.stat_exporter.stat_commit_request_and_timeout(request.get('method', '---'), resp_time_ms)
Please, check latest changes in develop.
`request` can be None (not the dict)

2022-04-06 17:22 UTC, afalaleev approved these changes

2022-04-06 17:22 UTC, afalaleev commented on proxy/plugin/solana_rest_api.py
> +        if succeed:
An additional `if` 
I think it is better to create two different methods - `_stat_tx_success()`  and `_stat_tx_failed()`

2022-04-06 19:40 UTC, merged