handle each potentially dangerous command
neonevm/proxy-model.py pull request #681
Opened 2022-03-28 13:36 UTC by inkognitotester

2022-03-28 14:55 UTC, vodolaz approved these changes

2022-03-28 16:46 UTC, rozhkovdmitrii requested changes

2022-03-28 16:46 UTC, rozhkovdmitrii commented on .buildkite/steps/full_test_suite/terraform-destroy.sh
> +# error handler
if you want to make the code more expressive just name the function `handle_error`. Please get rid of comments.

2022-03-28 16:46 UTC, rozhkovdmitrii commented on .buildkite/steps/full_test_suite/terraform-destroy.sh
> +    # Print error message and interrupt script
the same -  just get rid of this line

2022-03-28 16:46 UTC, rozhkovdmitrii commented on .buildkite/steps/full_test_suite/terraform-destroy.sh
> +    echo "Interrupt at step: $1"
echo "Interrupt at step. $1"

2022-03-28 16:46 UTC, rozhkovdmitrii commented on .buildkite/steps/full_test_suite/terraform-destroy.sh
> +check_res "Create directory for logs '$ARTIFACTS_LOGS'"
check_res "Failed to create artifacts dir at: '$ARTIFACTS_LOGS'"

2022-03-28 16:46 UTC, rozhkovdmitrii commented on .buildkite/steps/full_test_suite/terraform-destroy.sh
> +check_res "Dump solana logs to the file"
Failed to dump logs remotely at: ' ubuntu@${REMOTE_HOST}' with key file: '${SSH_KEY}'

2022-03-28 16:46 UTC, rozhkovdmitrii commented on .buildkite/steps/full_test_suite/terraform-destroy.sh
>  ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts
to be checked. Don't forget the context please

2022-03-28 16:46 UTC, rozhkovdmitrii commented on .buildkite/steps/full_test_suite/terraform-destroy.sh
> +check_res "Terraform init step"
Failed to proceed the terraform init step. TF_BACKEND_CONFIG: ${TF_BACKEND_CONFIG}

2022-03-28 16:46 UTC, rozhkovdmitrii commented on .buildkite/steps/full_test_suite/terraform-destroy.sh
> +check_res "Terraform destroy step"
Failed to proceed terraform destroy step

2022-03-29 07:49 UTC, rozhkovdmitrii approved these changes

2022-04-04 06:58 UTC, merged