#673 prometheus metrics in indexer
neonevm/proxy-model.py pull request #689
Opened 2022-03-31 14:26 UTC by otselnik

2022-04-07 14:03 UTC, rozhkovdmitrii requested changes

2022-04-07 14:03 UTC, rozhkovdmitrii commented on proxy/common_neon/solana_interactor.py
> +    def is_health(self) -> bool:
Isn't it better to just name it `is_healthy`

2022-04-07 14:03 UTC, rozhkovdmitrii commented on proxy/indexer/base_db.py
> +    def connected(self) -> bool:
`is_connected`

2022-04-07 14:03 UTC, rozhkovdmitrii commented on proxy/indexer/indexer.py
> +from proxy.statistics_exporter.prometheus_indexer_exporter import PrometheusExporter
Move it from here

2022-04-07 14:03 UTC, rozhkovdmitrii commented on proxy/indexer/indexer.py
> +        self.stat_exporter = PrometheusExporter()
Indexer should know nothing about statistics and Prometheus

2022-04-07 14:03 UTC, rozhkovdmitrii commented on proxy/indexer/indexer.py
> +    def iter_stat_info(self) -> Iterator[NeonTxObject]:
`iter_state_info`
`iter_neon_tx_object` 

**`iter_neon_tx_results`**
?

2022-04-07 14:03 UTC, rozhkovdmitrii commented on proxy/indexer/indexer.py
> +        self.commit_statistics()
`gather_neon_tx_data`, `process_neon_tx_data`, `process_collected_neon_txs`, `process_neon_txs`

**`process_neon_tx_results`**

2022-04-07 14:03 UTC, rozhkovdmitrii commented on proxy/indexer/indexer.py
> +        for stat_info in self.state.iter_stat_info():
`neon_tx_result`

2022-04-07 14:03 UTC, rozhkovdmitrii commented on proxy/indexer/indexer.py
> +            self.stat_exporter.stat_commit_count_sol_tx_per_neon_tx(tx_type, len(stat_info.used_ixs))
It can be more reasonable to put into the further processing all the `neon_tx_result` or the structure that is applicable on the next processing step.

`self._user.on_neon_tx_result(neon_tx_result)`
?

2022-04-07 14:03 UTC, rozhkovdmitrii commented on proxy/indexer/indexer.py
> +        self.stat_exporter.stat_commit_postgres_availability(self.db.status())
`self._user.on_db_status(db_status)`

2022-04-07 14:03 UTC, rozhkovdmitrii commented on proxy/indexer/indexer.py
> +        self.stat_exporter.stat_commit_solana_rpc_health(self.solana.is_health())
`self._user.on_solana_rpc_status`

2022-04-07 14:03 UTC, rozhkovdmitrii commented on proxy/prometheus.yml
> +  scrape_interval:     15s
move it into docker-compose directory on the top of the project, `docker-compose-neon-monitor`

2022-04-07 14:03 UTC, rozhkovdmitrii commented on proxy/indexer/indexer.py
> +
```python
from ..common_neon.data import NeonTrxResult

class IndexerApp(IIndexerUser):

    def __init__(self):
        self.neon_statistics = NeonStatistica()
        indexer = Indexer(solana_url, self)
        indexer.run()

    def on_neon_trx_result(self, neon_trx_result: NeonTrxResult):
        self.neon_statistics.on_txt_sol_spen(neon_trx_result)

    def on_neon_trx_db_status(self, neon_trx_db_status: bool):
        self.neon_statistics.on_neon_trx_db_status(neon_trx_db_status)
        
    def on_solana_status(self, solana_status: bool):
        self.neon_statistics.on_solana_status(solana_status)
```

2022-04-07 14:03 UTC, rozhkovdmitrii commented on proxy/indexer/indexer.py
> +
Move `IndexerApp`  into `indexer_app.py`

2022-04-09 10:30 UTC, rozhkovdmitrii commented on proxy/indexer/indexer_app.py
> +        self.neon_statistics.stat_commit_count_sol_tx_per_neon_tx(tx_type, len(neon_tx_result.used_ixs))
This logic should be left inside the indexer, this class supposes only calls redirection in it

2022-04-09 10:40 UTC, rozhkovdmitrii commented on proxy/indexer/indexer_app.py
> +        self.neon_statistics.stat_commit_count_sol_tx_per_neon_tx(tx_type, len(neon_tx_result.used_ixs))
This logic should be left inside the indexer, this class supposes only calls redirection in it. If it needs you can create statistic related type to express the neon transaction results or use existing one

2022-04-09 10:59 UTC, rozhkovdmitrii commented on proxy/prometheus.yml
> +  scrape_interval:     15s
May be the `statistics_exporter` directory?

2022-04-11 09:09 UTC, otselnik commented on proxy/indexer/indexer_app.py
> +        self.neon_statistics.stat_commit_count_sol_tx_per_neon_tx(tx_type, len(neon_tx_result.used_ixs))
You're right. Fixed it using `NeonTxStatData` class.

2022-04-11 09:09 UTC, otselnik commented on proxy/prometheus.yml
> +  scrape_interval:     15s
Sounds good.  `statistics_exporter/config`  i think is better.

2022-04-11 10:20 UTC, rozhkovdmitrii approved these changes

2022-04-11 12:17 UTC, merged