#635 Operator Accounts print utility
neonevm/proxy-model.py pull request #690
Opened 2022-03-31 20:41 UTC by otselnik

Executed with:
`python3 -m proxy.accounts_info`
Output:
```json
{
   "accounts":[
      {
         "solana_address":"5mPEmfbCfU3wpqHS6U6vzAXPNgw4UHBu1SQc5Zoz5su8",
         "neon_address":"0x07521c8ac9b1c55f6e2089bd78dfd702bb844f55",
         "neon_private":"0x07521c8ac9b1c55f6e20896d62b3fbd78dfd702bb844f5593850659883f74ac",
         "resource_keys":[
            "D7XJqP5CjPGRLJWw3SG11PX5cwtPG5qTZWJA5Rx6KVBt",
            "Csv4D5eHposSBmmLraD4jbwsPozL7GozTSPifkAGh8eQ",
            "7BFCCoYEbZC7v6cLuNbGUrUYVhtZse98VgedJ6Gbj4Pk",
            "5mPEmfbCfU3wpqHS6U6vzAXPNgw4UHBu1SQc5Zoz5su8"
         ]
      }
   ]
}
````

2022-04-02 18:32 UTC, afalaleev requested changes
Looks good! But:
- In JSON add:
--- balance of storage/holder accounts
--- solana private
--- total-balance in SOL available for tx processing
--- total-balance in SOL on storage/holder accounts
--- total-balance in NEON 
- Move this functionality to proxy-cli utility as a command 
- In proxy-cli utility add simple commands:
--- to print list of  `solana-address  solana-balance solana-strorage/holder-balance` + total balance
--- to print list of `neon-address neon-balance` +total balance 
--- to print list of `neon-private-key` (can be used to add account to metamask)
--- to print list of `solana-private-key` (can be used to add account to metamask)
--- to print list of `storage-accounts`
--- to print list of `holder-accounts`

2022-04-06 14:59 UTC, afalaleev commented on proxy-cli/__main__.py
>      operator_handler = OperatorHandler.init_args_parser(subparsers)
Remove operator_handler
It was created for info_handler.

2022-04-06 14:59 UTC, afalaleev commented on proxy-cli/info.py
> +            ret_js = self._all_info(args)
Only this case should print full json.
Other commands should print simple lines

2022-04-06 16:57 UTC, otselnik commented on proxy-cli/__main__.py
>      operator_handler = OperatorHandler.init_args_parser(subparsers)
done

2022-04-06 16:57 UTC, otselnik commented on proxy-cli/info.py
> +            ret_js = self._all_info(args)
fixed

2022-04-06 17:17 UTC, afalaleev submitted a review, later dismissed

2022-04-06 17:17 UTC, afalaleev commented on proxy-cli/__main__.py
>      operator_handler = OperatorHandler.init_args_parser(subparsers)
Remove operator_handler
It was created for info_handler.

2022-04-07 13:47 UTC, afalaleev approved these changes

2022-04-07 13:49 UTC, merged