#764 Decrease the storage usage for Solana receipts
neonevm/proxy-model.py pull request #769
Opened 2022-05-16 05:14 UTC by otselnik

2022-05-17 17:14 UTC, afalaleev requested changes
Looks good! But several issues should be fixed.

2022-05-17 17:14 UTC, afalaleev commented on proxy/indexer/indexer_base.py
> +                    self.solana_signatures.add_signature(tx_list[0][0], tx_list[0][1])
Solana blocks can contain a lot of transactions.
If block contain more than INDEXER_POOL_COUNT transactions, the table with solana signatures will have more than 1 record with the same block slot.
You should set in this place flag and save checkpoint only on changing of block slot.

2022-05-17 17:14 UTC, afalaleev commented on proxy/indexer/indexer_base.py
> +            opts["until"] = until
One month ago we fixed a bug with `until`.
Solana node returns two independent range of transactions in which the end of the first range was the begin of the second range, and at the same time the end of the second range was the begin of the first range.
For example:
```[tx1, tx2 ... tx3, tx4]  <-> [tx4, tx5 ... tx6, tx1]```

As a result, the indexer deadlooped on trying to get the signatures.
It is better to use only `before` and break on the getting `until`

2022-05-17 17:14 UTC, afalaleev commented on proxy/indexer/indexer_base.py
> +            signatures.append(signature)
This is only comment: you can return tx_list and reverse after getting receipts

2022-05-17 17:14 UTC, afalaleev commented on proxy/indexer/indexer_base.py
> +                break
As I understand, on the next call `get_tx_receipts()` , `gather_unknown_transaction()` will return the same list of transactions and they will be passed to the receipt parser?

2022-05-18 14:37 UTC, otselnik commented on proxy/indexer/indexer_base.py
> +            opts["until"] = until
fixed

2022-05-18 16:14 UTC, otselnik commented on proxy/indexer/indexer_base.py
> +                break
`self._maximum_tx` is overwritten every cycle and `gather_unknown_transaction` will return jnly new transactions till `self._maximum_tx`

2022-05-18 16:25 UTC, otselnik commented on proxy/indexer/indexer_base.py
> +                    self.solana_signatures.add_signature(tx_list[0][0], tx_list[0][1])
Fixed by making slot unique.

2022-05-18 16:26 UTC, otselnik commented on proxy/indexer/indexer_base.py
> +            signatures.append(signature)
Optimized

2022-05-19 06:15 UTC, afalaleev requested changes

2022-05-19 06:15 UTC, afalaleev commented on proxy/indexer/indexer_base.py
> +                break
Ok.
We can set_maximum_tx in two cases:
- on the break
- on the end of loop

Currently, we have an surplus update on each call.

2022-05-19 06:15 UTC, afalaleev commented on proxy/indexer/indexer_base.py
> +            opts["until"] = until
I don't see the fix, the source code is the same

2022-05-19 06:17 UTC, otselnik commented on proxy/indexer/indexer_base.py
> +            opts["until"] = until
https://github.com/neonlabsorg/proxy-model.py/blob/764_do_not_store_solana_receipts_in_indexer/proxy/indexer/indexer_base.py#L146

2022-05-19 06:22 UTC, otselnik commented on proxy/indexer/indexer_base.py
> +                break
But it not processed yet and must be processed on next cycle

2022-05-19 06:27 UTC, otselnik commented on proxy/indexer/indexer_base.py
> +                break
I update maximum_tx on each cycle for case when outer loop processing receipts catches error and throws. In this case if i would updated maximum_tx on end of loop `gather_unknown_transactions` will request same amount of signatures as previous call.

2022-05-19 06:33 UTC, otselnik commented on proxy/indexer/indexer_base.py
> +                break
I must agree that it is pointless, since when new transactions will come there will be no profit

2022-05-20 10:57 UTC, afalaleev approved these changes

2022-05-20 14:47 UTC, merged