Use logs of Tx to extract events and results
neonevm/proxy-model.py pull request #776
Opened 2022-05-24 07:04 UTC by vakond

Parse logMessages instead of parsing dummy EVM Loader instructions OnResult & OnEvent.

2022-06-26 11:04 UTC, otselnik commented on proxy/indexer/indexer.py
> +
Remove lines

2022-06-26 11:04 UTC, otselnik commented on proxy/indexer/indexer.py
> +
Remove commented lines

2022-06-26 11:04 UTC, otselnik commented on proxy/indexer/indexer.py
> +        the parsing order can be other than the execution orderOnRe
Typo  `order` `orderOnRe`

2022-06-26 11:04 UTC, otselnik commented on proxy/indexer/indexer.py
>                  yield evm_ix_idx
I think `self.evm_ix_idx` could be used instead of `evm_ix_idx`
```python
                self.evm_ix_idx += 1
                yield self.evm_ix_idx
```

2022-06-27 08:01 UTC, rozhkovdmitrii commented on .buildkite/steps/revision.sh
> +set ${NEON_EVM_COMMIT:=b36ecae109da43fced2e2bf9fc51f256b21b9964}
It will have to be changed further

2022-06-27 08:11 UTC, vakond commented on .buildkite/steps/revision.sh
> +set ${NEON_EVM_COMMIT:=b36ecae109da43fced2e2bf9fc51f256b21b9964}
Sure. After the review is completed, we'll change this commit to standard and merge to develop.

2022-06-27 20:42 UTC, rozhkovdmitrii requested changes

2022-06-27 20:42 UTC, rozhkovdmitrii commented on proxy/common_neon/utils/utils.py
> +    """
For this type of doc string we use single line

2022-06-27 20:42 UTC, rozhkovdmitrii commented on proxy/common_neon/utils/utils.py
> +    def decode(self, neon_sign: str, tx: Dict[Any, Any], ix_idx=-1) -> NeonTxResultInfo:
All the decoding stuff is the part of `DummyIxDecoder` like `_init_tx_from_holder` isn't it? Bring it there please

2022-06-27 20:42 UTC, rozhkovdmitrii commented on proxy/common_neon/utils/utils.py
> +    """
Single line docstring

2022-06-27 20:42 UTC, rozhkovdmitrii commented on proxy/common_neon/utils/utils.py
> +    for i, s in enumerate(data):
try:
    exit_status_b64 = next(data)
    ...
    gas_used_b64 = next(data)
    ...
except StopIteration:
    logger.error("Failed to decode contract

2022-06-27 20:42 UTC, rozhkovdmitrii commented on proxy/common_neon/utils/utils.py
> +def unpack_return(data: Iterable[str]) -> ReturnDTO:
```
@logged_group("neon.Indexer")
def decode_neon_tx_return(data: Iterable[str], logger) -> ReturnDTO:
```

I suggest to bring it into `common_neon/evm_decoder.py`

2022-06-27 20:42 UTC, rozhkovdmitrii commented on proxy/common_neon/utils/utils.py
> +class ReturnDTO:
I'm not sure it's the right place for it. `common_neon/data.py`
`ReturnDTO` is the right name.`NeonTxReturn`?

2022-06-27 20:42 UTC, rozhkovdmitrii commented on proxy/common_neon/utils/utils.py
> +    count_topics: int = 0
I certainly not sure you really need the `count_topics` field here

2022-06-27 20:42 UTC, rozhkovdmitrii commented on proxy/common_neon/utils/utils.py
> +    for i, s in enumerate(data):
Prefer `next` to read sequential member of data. Loop for these purposes looks ... hm ... strange

2022-06-27 20:42 UTC, rozhkovdmitrii commented on proxy/common_neon/utils/utils.py
> +def process_logs(logs: List[str]) -> List[LogIxDTO]:
The name should be started with `decode` like the other decoding functions. Look at them in indexer

2022-06-27 20:42 UTC, rozhkovdmitrii commented on proxy/common_neon/utils/utils.py
> +def process_logs(logs: List[str]) -> List[LogIxDTO]:
Shouldn't it be covered with tests?

2022-06-27 20:42 UTC, rozhkovdmitrii commented on proxy/common_neon/utils/utils.py
> +        m = program_invoke.match(line)
`match = ...` ?

2022-06-27 20:42 UTC, rozhkovdmitrii commented on proxy/common_neon/utils/utils.py
> +            if program_id == EVM_LOADER_ID:
Should the current log be skipped if it's not the EVM log?

2022-06-27 20:42 UTC, rozhkovdmitrii commented on proxy/common_neon/utils/utils.py
> +    program_success = re.compile(r'^Program (\w+) success')
Is it really needed?

2022-06-27 20:42 UTC, rozhkovdmitrii commented on proxy/common_neon/utils/utils.py
> +    def decode(self, neon_sign: str, tx: Dict[Any, Any], ix_idx=-1) -> NeonTxResultInfo:
`neon_sign` or `neon_tx_hash` ?

2022-06-27 20:42 UTC, rozhkovdmitrii commented on proxy/common_neon/utils/utils.py
> +class EventDTO:
Get rid of `DTO` suffix please. It'll also be migrated to indexer. `NeonEvent` put it in `common_data/data.py`

2022-06-27 20:42 UTC, rozhkovdmitrii commented on proxy/common_neon/utils/utils.py
> +def unpack_event_log(data: Iterable[str]) -> EventDTO:
`decode_neon_event`

2022-06-27 20:42 UTC, rozhkovdmitrii commented on proxy/common_neon/utils/utils.py
> +                assert False, f'Wrong mnemonic {mnemonic}'
It couldn't be assert because this data come over the network. This case should be logged as error and raised an Exception. We make assert when it's developing error

2022-06-27 20:42 UTC, rozhkovdmitrii commented on proxy/common_neon/utils/utils.py
> +            for e in log_ix.event_dtos:
What about different `_decode_event`?

2022-06-27 20:42 UTC, rozhkovdmitrii commented on proxy/testing/test_indexer_work.py
> +        self.assertEqual(len(call2_receipt['logs']), 1)
Shouldn't address, topics and data be checked?
Does it have `neon_tx_return`?

2022-06-27 20:45 UTC, rozhkovdmitrii commented on proxy/common_neon/utils/utils.py
> +                self.gas_used = hex(log_ix.return_dto.gas_used)
What about historical `_decode_return` - can it be used here?

2022-06-28 08:19 UTC, rozhkovdmitrii commented on proxy/common_neon/utils/utils.py
> +            program_id = m.group(1) # do nothing
will gone

2022-06-28 08:20 UTC, rozhkovdmitrii commented on proxy/common_neon/utils/utils.py
> +                    # 'blockNumber': block_number, # set when transaction found
If it is not needed, cut it out please

2022-06-28 08:24 UTC, otselnik commented on proxy/common_neon/utils/utils.py
> +    def decode(self, neon_sign: str, tx: Dict[Any, Any], ix_idx=-1) -> NeonTxResultInfo:
It should be here. This decode function relates to result and It is part of proxy too.

2022-06-28 18:21 UTC, vakond commented on proxy/common_neon/utils/utils.py
> +                self.gas_used = hex(log_ix.return_dto.gas_used)
No, because _decode_return takes raw binary data, and decode takes textual data encoded as base64. Formats of the encodings are different in the two cases.

2022-06-28 18:24 UTC, vakond commented on proxy/common_neon/utils/utils.py
> +            for e in log_ix.event_dtos:
Again, existing _decode_event works with data in different format.

2022-06-29 07:14 UTC, rozhkovdmitrii commented on proxy/common_neon/utils/utils.py
> +            for e in log_ix.event_dtos:
It doesn't work with anything anywhere. It should be corrected to be able to work with data in proper format and moved away where all decoding stuff is.

2022-06-29 07:20 UTC, rozhkovdmitrii commented on proxy/common_neon/utils/utils.py
> +                self.gas_used = hex(log_ix.return_dto.gas_used)
the same is for _decode_event

2022-06-29 07:25 UTC, rozhkovdmitrii commented on proxy/common_neon/evm_decoder.py
> +                logger.error(f'Wrong mnemonic {mnemonic}')
logger.error(f'Failed to decode log instructions, unexpected mnemonic: {mnemonic}, instruction line: {line}')

2022-06-29 08:13 UTC, rozhkovdmitrii commented on proxy/common_neon/evm_decoder.py
> +def process_logs(logs: List[str], logger) -> List[NeonLogIx]:
decode_neon_log_instructions

2022-06-29 08:15 UTC, rozhkovdmitrii commented on proxy/common_neon/evm_decoder.py
> +def decode(info: NeonTxResultInfo, neon_sign: str, tx: Dict[Any, Any], ix_idx=-1) -> NeonTxResultInfo:
Decode what?

`decode_neon_tx_result`

2022-06-29 08:33 UTC, otselnik commented on proxy/indexer/pythnetwork.py
> +        result[key.decode_neon_tx_result('utf-8')] = value.decode_neon_tx_result('utf-8')
wrong replace

2022-06-29 08:48 UTC, vakond commented on proxy/indexer/pythnetwork.py
> +        result[key.decode_neon_tx_result('utf-8')] = value.decode_neon_tx_result('utf-8')
Sorry, tried automatic refactoring :). Reverted.

2022-06-29 08:56 UTC, otselnik submitted a review, later dismissed
Everything is ok for me.
Waiting for @rozhkovdmitrii comments fixes and do not forget about returning
`set ${NEON_EVM_COMMIT:=latest}` before merging

2022-06-29 18:50 UTC, vakond commented on proxy/common_neon/utils/utils.py
> +            for e in log_ix.event_dtos:
Removed unused functions.

2022-06-30 11:58 UTC, rozhkovdmitrii commented on proxy/common_neon/evm_decoder.py
> +def decode_neon_log_instructions(logs: List[str], logger) -> List[NeonLogIx]:
`... , *, logger) -> List[NeonLogIx]:` - logger is not positional argument it can only be keyword

2022-06-30 11:58 UTC, rozhkovdmitrii commented on proxy/common_neon/data.py
> +    address: bytes = None
`Optional[bytes]` or `b""` as default

2022-06-30 11:58 UTC, rozhkovdmitrii commented on proxy/common_neon/data.py
> +    topics: List[bytes] = None
`Optional[List[bytes]]` or `[]` as default

2022-06-30 11:58 UTC, rozhkovdmitrii commented on proxy/common_neon/data.py
> +    log_data: bytes = None
Optional[bytes] or b"" as default

2022-06-30 11:58 UTC, rozhkovdmitrii commented on proxy/common_neon/data.py
> +    neon_return: NeonReturn = None
`Optional[NeonReturn]` or `field(default_factory=NeonReturn)`as default

2022-06-30 11:58 UTC, rozhkovdmitrii commented on proxy/common_neon/evm_decoder.py
> +from .environment_data import EVM_LOADER_ID
single separator line

2022-06-30 11:58 UTC, rozhkovdmitrii commented on proxy/common_neon/data.py
> +    exit_status: int = 0
Just a question can it be Enum like a `MPRequestType`

2022-06-30 11:58 UTC, rozhkovdmitrii commented on proxy/common_neon/data.py
> +# Description: contains simple structs.
We have no agreement for headers like that, let's get rid of it yet please

2022-06-30 11:58 UTC, rozhkovdmitrii commented on proxy/common_neon/data.py
> +class NeonReturn:
Didn't it be supposed to be renamed to `NeonTxReturn`

2022-06-30 11:58 UTC, rozhkovdmitrii commented on proxy/common_neon/evm_decoder.py
> +    '''Unpacks base64-encoded return data'''
#### [From here](https://peps.python.org/pep-0257/#what-is-a-docstring)

For consistency, always use """triple double quotes""" around docstrings. Use r"""raw triple double quotes""" if you use any backslashes in your docstrings. For Unicode docstrings, use u"""Unicode triple-quoted strings""".

There are two forms of docstrings: one-liners and multi-line docstrings.

2022-06-30 12:56 UTC, vakond commented on proxy/common_neon/data.py
> +    exit_status: int = 0
Theoretically yes, it can be enum. For instance, the evm_loader code contains somewhere:

```
let (exit_message, exit_status) = match exit_reason {
    ExitReason::Succeed(success_code) => {
        match success_code {
            ExitSucceed::Stopped => {("ExitSucceed: Machine encountered an explict stop.", 0x11_u8)},
            ExitSucceed::Returned => {("ExitSucceed: Machine encountered an explict return.", 0x12)},
            ExitSucceed::Suicided => {("ExitSucceed: Machine encountered an explict suicide.", 0x13)},
        }
    },
```

But it's an open question if we want to drag this in the proxy.

2022-06-30 13:37 UTC, rozhkovdmitrii commented
We need to crate a group of CI tests. The idea is in making a simple contract that is like a `Storage` contract that emits and/or reverts with a huge peace of data. This data can consists or of 5KB or more either in other case exceeds 10Kb to show the solana limitation. 

If we can't prove the solution is working because of "different" problems in life testing Diamond contract the only thing we have to get done to prove the solution is fulfilled is to make this test.

2022-07-06 09:23 UTC, rozhkovdmitrii commented on proxy/common_neon/utils/utils.py
> +    def _print_logs(self, logs: List[str]):
where is it used?

2022-07-06 09:27 UTC, rozhkovdmitrii commented on proxy/common_neon/data.py
> +    neon_return: NeonReturn = None
Do not see any changes

2022-07-06 09:27 UTC, rozhkovdmitrii commented on proxy/common_neon/data.py
> +    log_data: bytes = None
No changes

2022-07-06 09:27 UTC, rozhkovdmitrii commented on proxy/common_neon/data.py
> +    topics: List[bytes] = None
No any changes

2022-07-06 09:28 UTC, rozhkovdmitrii commented on proxy/common_neon/data.py
> +    address: bytes = None
Nothing changed

2022-07-06 09:28 UTC, rozhkovdmitrii commented on proxy/common_neon/evm_decoder.py
> +def decode_neon_log_instructions(logs: List[str], logger) -> List[NeonLogIx]:
Nothing changed

2022-07-06 09:32 UTC, rozhkovdmitrii commented on proxy/common_neon/utils/utils.py
> +    '''Provides smart getting values from python dictionary'''
https://github.com/neonlabsorg/proxy-model.py/pull/776#discussion_r910919926

2022-07-06 09:33 UTC, vakond commented on proxy/common_neon/utils/utils.py
> +    def _print_logs(self, logs: List[str]):
It was used for debugging puproses and may be useful in the future.

2022-07-06 09:37 UTC, rozhkovdmitrii commented on proxy/common_neon/utils/utils.py
> +    def _print_logs(self, logs: List[str]):
IMHO if you don't use it it's garbage

2022-07-06 09:38 UTC, vakond commented on proxy/common_neon/utils/utils.py
> +    '''Provides smart getting values from python dictionary'''
Changed to """..."""

2022-07-06 10:17 UTC, vakond commented on proxy/common_neon/utils/utils.py
> +    def _print_logs(self, logs: List[str]):
Removed it:
```
def _print_logs(self, logs: List[str]):
    for line in logs:
        if (line.find("invoke") != -1) or (line.find("success") != -1) or (line.find("failed") != -1) or (line.find("Program data") != -1):
            self.debug(f">>>> {line}")
```

2022-07-07 08:50 UTC, vakond commented on proxy/common_neon/evm_decoder.py
> +def decode_neon_log_instructions(logs: List[str], logger) -> List[NeonLogIx]:
I've tried it - doesn't work.

2022-07-07 08:50 UTC, vakond commented on proxy/common_neon/data.py
> +    topics: List[bytes] = None
I've tried this - doesn't work.

2022-07-07 08:50 UTC, vakond commented on proxy/common_neon/data.py
> +    log_data: bytes = None
I've tried this - doesn't work.

2022-07-07 08:50 UTC, vakond commented on proxy/common_neon/data.py
> +    neon_return: NeonReturn = None
I've tried this - doesn't work.

2022-07-15 06:00 UTC, vakond commented on proxy/common_neon/utils/utils.py
> +class ReturnDTO:
Already renamed.

2022-07-15 06:09 UTC, vakond commented on proxy/common_neon/utils/utils.py
> +    count_topics: int = 0
It has a purpose to control maximal number of topics

2022-07-15 06:10 UTC, vakond commented on proxy/common_neon/utils/utils.py
> +    for i, s in enumerate(data):
Index is essential here.

2022-07-15 06:11 UTC, vakond commented on proxy/common_neon/utils/utils.py
> +def process_logs(logs: List[str]) -> List[LogIxDTO]:
Yes

2022-07-15 06:12 UTC, vakond commented on proxy/common_neon/utils/utils.py
> +    program_success = re.compile(r'^Program (\w+) success')
Removed.

2022-07-15 06:12 UTC, vakond commented on proxy/common_neon/utils/utils.py
> +        m = program_invoke.match(line)
Renamed

2022-07-15 06:14 UTC, vakond commented on proxy/common_neon/utils/utils.py
> +            if program_id == EVM_LOADER_ID:
It's skipped

2022-07-15 06:18 UTC, vakond commented on proxy/common_neon/utils/utils.py
> +    def decode(self, neon_sign: str, tx: Dict[Any, Any], ix_idx=-1) -> NeonTxResultInfo:
neon_sign is "traditional" name here

2022-07-15 06:19 UTC, vakond commented on proxy/testing/test_indexer_work.py
> +        self.assertEqual(len(call2_receipt['logs']), 1)
It really doesn't needed to this test. But can be added later.

2022-07-18 16:57 UTC, rozhkovdmitrii approved these changes

2022-07-19 07:23 UTC, merged