#721 sort by sender nonce gas(testing purpose)
neonevm/proxy-model.py pull request #784
Opened 2022-05-31 13:08 UTC by otselnik

2022-06-07 11:01 UTC, rozhkovdmitrii requested changes

2022-06-07 11:01 UTC, rozhkovdmitrii commented on proxy/mempool/mempool.py
> +from typing import List, Set, Tuple, Dict
`Set` is not used anywhere

2022-06-07 11:01 UTC, rozhkovdmitrii commented on proxy/mempool/mempool.py
>  import bisect
`bisect` is not used anywhere

2022-06-07 11:01 UTC, rozhkovdmitrii commented on proxy/mempool/mempool.py
> +from .mempool_scheduler import MPNeonTxScheduler
Don't you mind to rename it to just MPTxSchedule

2022-06-07 11:01 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_scheduler.py
> +    def __eq__(self, other):
annotation for `other`

2022-06-07 11:01 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_scheduler.py
> +    def __lt__(self, other):
annotation for `other`

2022-06-07 11:01 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_scheduler.py
> +from .mempool_api import MPTxRequest
Add blank line before

2022-06-07 11:01 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_scheduler.py
> +        self.txs = SortedList()
```
self.txs:  SortedList[MPtxRequest] = SortedList()
```

2022-06-07 11:01 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_scheduler.py
> +        self.address = address
self.address: str = address

2022-06-07 11:01 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_scheduler.py
> +        return self.txs.pop(0)
Shouldn't it be checked before retrieving

2022-06-07 11:01 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_scheduler.py
> +        self.txs.add(tx)
It's unfortunate thing that the `insert` is depricated :(
It can be implemented in more effective way just with `bisect` and no new requirements

... or using pandas `dataframes`

2022-06-07 11:01 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_scheduler.py
> +        if len(self.txs) == 0:
Does it mean there is an programing error if the condition is True?
```
assert(len(self.txt) == 0)
```

2022-06-07 11:01 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_scheduler.py
> +        self.senders.sort()
Seems like it can be written better.
1. Get or create sender
2. Add tx

2022-06-07 11:01 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_scheduler.py
> +        self.senders.sort()
Would it be faster if the sender was removed from the first position and inserted the other by the bisect.insort.
Can it prevent from creating a new class `MPSenderTXs`. 
Just a single change in just a single place.

```
l = [[500, 200, 300], [450, 200], [300, 600]]
v = l[0][1:]
l = l[1:]
bisect.insort(l, v, key=lambda v: -v[0])
```

2022-06-07 11:01 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_api.py
> +        self.nonce      = self.neon_tx.nonce
extra alignment

2022-06-07 11:12 UTC, rozhkovdmitrii commented on proxy/mempool/mempool.py
>          # signer -> pending_tx_counter
There is no need to store separate counter for pending transaction more. Pending transaction count should be gotten from MPTxSchedule

2022-06-09 05:30 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_scheduler.py
> +            del self.senders[0]
What if the current transaction from this sender is executing?

2022-06-09 16:52 UTC, otselnik commented on proxy/mempool/mempool_scheduler.py
> +        if len(self.txs) == 0:
nope

2022-06-09 16:53 UTC, otselnik commented on proxy/mempool/mempool_scheduler.py
> +        return self.txs.pop(0)
What should be checked?

2022-06-15 14:45 UTC, otselnik commented
Implemented in 
https://github.com/neonlabsorg/proxy-model.py/pull/795

2022-06-15 14:45 UTC, closed without merging