724 bring the neon transaction back to pending
neonevm/proxy-model.py pull request #804
Opened 2022-06-20 15:20 UTC by ivandzen

2022-06-21 08:35 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_executor.py
> +from proxy.common_neon.solana_tx_list_sender import BlockedAccountsError
`from ..common_neon` group it please with the other relative imports

2022-06-21 13:17 UTC, otselnik requested changes

2022-06-21 13:17 UTC, otselnik commented on proxy/mempool/mempool_executor.py
> +                return await self.execute_neon_tx(mempool_request, skip_writing_holder=True)
It won't release executor to process other transactions while it waits for the transaction to be unlocked.

2022-06-21 13:20 UTC, rozhkovdmitrii requested changes

2022-06-21 13:20 UTC, rozhkovdmitrii commented on proxy/common_neon/solana_tx_list_sender.py
> +
two blank line

2022-06-21 13:20 UTC, rozhkovdmitrii commented on proxy/common_neon/solana_tx_list_sender.py
> -            time.sleep(0.4)  # one block time
`time.sleep(SolTxListSender.ONE_BLOCK_SEC)`

2022-06-21 13:20 UTC, rozhkovdmitrii commented on proxy/mempool/transaction_sender.py
> +    def __init__(self, exec_cfg: NeonTxExecCfg, neon_tx_sender: NeonTxSender, skip_writing_holder = False):
Isn't the `skip_writing_holder` the part of NeonTxExecCfg

2022-06-21 13:20 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_executor.py
> +                await asyncio.sleep(0.4)
It seems like executor won't be used on the MemPool until it accounts get freed. Why don't you return the result to the MemPool as it has been designed and don't allow the MemPool to decide what to do?

2022-06-21 13:22 UTC, rozhkovdmitrii commented
`BlockedAccount` result status should covered by tests at first to make it able to be checked al the time and to express the what you want more transparently

2022-06-26 10:35 UTC, otselnik requested changes

2022-06-26 10:35 UTC, otselnik commented on proxy/mempool/mempool.py
> +                self._on_blocked_accounts_result(mp_request, mp_tx_result)
Shouldn't it be:
```python
self._executor.release_resource(resource_id)
self._on_blocked_accounts_result(mp_request, mp_tx_result)
```

2022-06-26 10:35 UTC, otselnik commented on proxy/mempool/mempool_executor.py
> +            tx_sender.execute(neon_tx_cfg, emulating_result, skip_writing_holder)
Looks like every retry new resource will be locked without unlocking previous try resource.

2022-06-28 14:24 UTC, rozhkovdmitrii commented on proxy/mempool/mempool.py
> +                self._on_blocked_accounts_result(mp_request, mp_tx_result)
done

2022-06-28 14:25 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_executor.py
> +            tx_sender.execute(neon_tx_cfg, emulating_result, skip_writing_holder)
done

2022-06-29 07:20 UTC, afalaleev requested changes
Why so many error/warnings in the source code?
Such approach makes impossible to create an automation tool to analyze the stable working of the proxy on production.

2022-06-29 07:20 UTC, afalaleev commented on proxy/common_neon/config.py
>      def get_evm_count(self) -> Optional[int]:
For what did you add the additional abstraction layer in face of IConfig interface in the same file with the one realization?
Why does it return Optional[] as results, when other parts of source code doesn't ready for such logic?
Why is 'number of evms' converted into 'number of evm steps' in other parts of the source code?

2022-06-29 07:20 UTC, afalaleev commented on proxy/common_neon/solana_tx_list_sender.py
> +        self.blocked_accounts: List[str] = blocked_accounts
It isn't a list of blocked accounts it is a list of receipts with blocked accounts.

2022-06-29 07:20 UTC, afalaleev commented on proxy/common_neon/solana_tx_list_sender.py
> +            raise BlockedAccountsError(self._blocked_account_list)
Sender contains list of transaction and receipts for them.

2022-06-29 07:20 UTC, afalaleev commented on proxy/common_neon/solana_tx_list_sender.py
> +        self.blocked_accounts: List[str] = blocked_accounts
Are they really needed on the high level of tx processing?

2022-06-29 07:20 UTC, afalaleev commented on proxy/mempool/operator_resource_list.py
> +            self.warning(f"Reentering in active resource: {self.resource}")
Why the level of log is warning?
It is a normal case in the logic of processing.
Several times we tried to add an automation tool to analyze logs of proxy, but logs contain a lot of records with warning/error levels which shouldn't trigger the automation tool.

2022-06-29 07:20 UTC, afalaleev commented on proxy/mempool/mempool.py
> +        self.warning(f"For tx: {mp_tx_request.log_str} - got blocked account transaction status: {mp_tx_result.data}. "
This is a debug log record, not a warning.

2022-06-29 07:20 UTC, afalaleev commented on proxy/mempool/mempool_executor.py
> +                self.warning(f"Blocked accounts: {err.blocked_accounts}, send BlockedAccount result back to the MemPool")
This is a debug log record.

2022-06-29 07:20 UTC, afalaleev commented on proxy/mempool/mempool_schedule.py
> +            self.warning(f"Failed drop request, no sender by sender_address: {mp_tx_request.sender_address}")
This is a debug log record.

2022-06-29 07:20 UTC, afalaleev commented on proxy/mempool/mempool_schedule.py
> +            self.error(f"Failed reschedule, no sender by sender_address: {sender_address}")
This is a debug log record.

2022-06-29 07:20 UTC, afalaleev commented on proxy/mempool/mempool.py
> +        self.warning(f"For tx: {mp_tx_request.log_str} - got blocked account transaction status: {mp_tx_result.data}. "
It doesn't break the logic of the program, so it doesn't trigger a high level automation tool.

2022-06-29 07:20 UTC, afalaleev commented on proxy/mempool/mempool_schedule.py
> +            self.error(f"Failed to reschedule tx, processing tx has different nonce: {self._processing_tx.nonce} than: {nonce}")
The same ....

2022-06-29 12:57 UTC, rozhkovdmitrii commented on proxy/common_neon/config.py
>      def get_evm_count(self) -> Optional[int]:
> For what did you add the additional abstraction layer in face of IConfig interface in the same file with the one realization?

1. I did that to be able to to mock config in testing purposes without relating to original one
2. I did that to have checks for all the methods are implemented

> Why does it return Optional[] as results, when other parts of source code doesn't ready for such logic?

You are right should add all the required checks in all the places where it's used. I'm already fixing it.

> Why is 'number of evms' converted into 'number of evm steps' in other parts of the source code?

"Other parts of the source code" is the only `NeonTxSender` constructorю. I tried to shorten the `get_evm_steps_count` and now I see if you are focused on it - it will be better to not shorten the name and fix the docstring as well. Thank you!

2022-06-29 13:21 UTC, rozhkovdmitrii commented on proxy/common_neon/config.py
>      def get_evm_count(self) -> Optional[int]:
I see `steps` are stored as class fields everywhere and the concept is to get it only from the Config through the interface where it needed, the concept is to make it easy to substitute only the IConfig in tests - not the `NeonTxSender`. Because it's not a part of NeonTxSender it's a config. But I can't do all the refactoring in this pull request. A can only prepare the interface and be able do it further.

2022-06-29 13:36 UTC, rozhkovdmitrii commented on proxy/common_neon/solana_tx_list_sender.py
> +        self.blocked_accounts: List[str] = blocked_accounts
Now I see it's not just a list. It's more like a list of transactions. It's a pity. I just wanted them to be logged to make us aware what accounts are blocked more frequently than the others

2022-06-29 19:44 UTC, rozhkovdmitrii commented on proxy/mempool/operator_resource_list.py
> +            self.warning(f"Reentering in active resource: {self.resource}")
It's not a normal case, furthermore it's rather assertion if `self._resource is not None`. That's why I'll cut this check of at all.

2022-06-29 19:53 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_schedule.py
> +            self.error(f"Failed reschedule, no sender by sender_address: {sender_address}")
If somebody tries to reschedule transaction with unknown sender it's certainly a error we should be concerned about

2022-06-29 19:55 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_schedule.py
> +            self.error(f"Failed to reschedule tx, processing tx has different nonce: {self._processing_tx.nonce} than: {nonce}")
Only the processing transaction can be rescheduled, that's why If somebody tries to reschedule transaction with wrong nonce it's a real problem we should know.

2022-06-29 20:00 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_schedule.py
> +            self.warning(f"Failed drop request, no sender by sender_address: {mp_tx_request.sender_address}")
If somebody tries to drop request with unknown sender away it's certainly a problem we should know

2022-06-29 20:00 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_executor.py
> +                self.warning(f"Blocked accounts: {err.blocked_accounts}, send BlockedAccount result back to the MemPool")
done

2022-06-29 20:00 UTC, rozhkovdmitrii commented on proxy/mempool/mempool.py
> +        self.warning(f"For tx: {mp_tx_request.log_str} - got blocked account transaction status: {mp_tx_result.data}. "
done

2022-06-29 20:04 UTC, rozhkovdmitrii commented on proxy/common_neon/solana_tx_list_sender.py
> +            raise BlockedAccountsError(self._blocked_account_list)
Got rid of blocked_account list inside the BlockedAccountsError

2022-07-04 04:08 UTC, afalaleev commented on proxy/common_neon/solana_tx_list_sender.py
> +        self.blocked_accounts: List[str] = blocked_accounts
You can get the list of accounts from the transaction header.
Transaction can't get access to an account that isn't listed in the header.

2022-07-04 05:45 UTC, afalaleev commented on proxy/mempool/operator_resource_list.py
> +            self.warning(f"Reentering in active resource: {self.resource}")
The base logic was another.
The worker has the local operator-list, and it returns the same resource after once it was selected.
If you changed the logic by moving the operator-list on a high level, you should remove the `self._resource` from the scope of the operator-list.

2022-07-04 05:45 UTC, afalaleev commented on proxy/mempool/mempool_schedule.py
> +            self.error(f"Failed reschedule, no sender by sender_address: {sender_address}")
Ok, let's merge as is. 
On merging to develop I will check the level of all log records.
As I see there are a lot of warning and errors which will happen on live system without any reason.

2022-07-04 05:45 UTC, afalaleev commented on proxy/mempool/mempool_schedule.py
> +            self.error(f"Failed to reschedule tx, processing tx has different nonce: {self._processing_tx.nonce} than: {nonce}")
Skipped, will be reviewed later.

2022-07-04 05:45 UTC, afalaleev commented on proxy/mempool/mempool_schedule.py
> +            self.warning(f"Failed drop request, no sender by sender_address: {mp_tx_request.sender_address}")
Skipped, will be reviewed later on merging to develop.

2022-07-04 05:49 UTC, rozhkovdmitrii commented on proxy/mempool/operator_resource_list.py
> +            self.warning(f"Reentering in active resource: {self.resource}")
Yeah, and I'm doing it right now in the OperatorResourceList related issue

2022-07-04 06:40 UTC, afalaleev approved these changes

2022-07-04 10:28 UTC, afalaleev requested changes

2022-07-04 10:28 UTC, afalaleev commented on proxy/mempool/mempool_schedule.py
>              self.erorr("Failed to drop last request from empty sender tx pool")
`erorr` -> `error'

2022-07-04 10:28 UTC, afalaleev commented on proxy/mempool/mempool_schedule.py
>              self.warning(f"Failed to drop last request away: {self._processing_tx.log_str} - processing")
It is normal case when scheduler has one transaction in the process.
So that `warning` will be in logs in many many cases.

2022-07-04 10:43 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_schedule.py
>              self.erorr("Failed to drop last request from empty sender tx pool")
OMG!!! Thank you very much!!!!

2022-07-04 10:44 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_schedule.py
>              self.warning(f"Failed to drop last request away: {self._processing_tx.log_str} - processing")
> It is normal case when scheduler has one transaction in the process. So that `warning` will be in logs in many many cases.

It's warning not for us but for operator like all the warnings, isn't it?

2022-07-04 10:48 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_schedule.py
>              self.warning(f"Failed to drop last request away: {self._processing_tx.log_str} - processing")
It's warning not for us but for operator like all the warnings, isn't it?
This case in my opinion has to be shown to operator as warning and he should perform the step to prevent these situation.

2022-07-04 10:51 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_schedule.py
>              self.erorr("Failed to drop last request from empty sender tx pool")
solved

2022-07-04 11:01 UTC, otselnik approved these changes

2022-07-04 11:32 UTC, afalaleev requested changes

2022-07-04 11:32 UTC, afalaleev commented on proxy/mempool/mempool_schedule.py
>              self.warning(f"Failed to drop last request away: {self._processing_tx.log_str} - processing")
You call this method from `_check_oversized_and_reduce(self)` without preventing the warning: 
https://github.com/neonlabsorg/proxy-model.py/blob/cee78838ff9a4ac1c97b8f0fcd50f719606d0835/proxy/mempool/mempool_schedule.py#L156

It will be called in anyway.
An operator will see a lot of warnings in the log, and the operator can't prevent these warnings by proxy configuration.
As a result, he/she won't use the logs from proxy to analyze the liveness of the proxy.

For the logic from you source code this warning is debug, that show you why this sender is skipped for removing from the mempool.
For an operator it doesn't help.
IMHO, logs should help an automation tools and operators to configure the proxy. You should think about logs from the operator's point of view, not from testing purposes of development. Logs will be used by operators, not by developers.

If you source code has so much warnings/errors it isn't production ready because it has a lot of invariants for which it is not ready.

2022-07-04 12:53 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_schedule.py
>              self.warning(f"Failed to drop last request away: {self._processing_tx.log_str} - processing")
Done. Introduced mempool capacity config

2022-07-04 13:37 UTC, afalaleev approved these changes

2022-07-05 05:49 UTC, afalaleev requested changes

2022-07-05 05:49 UTC, afalaleev commented on proxy/common_neon/environment_utils.py
> +            logger.error(f"Failed to read sol_account: {name}, that is not a file")
Again - why is there the error level message?
Function reads files in incremental mode - until the file with index doesn't exist, it is a condition for exit from the function.
And now in logs each time we see the error log record. 
For what?
How can operator prevent this situation?
If you want to change the logic - read the list of files and parse them - ok, you can do it. But in this case you should change logic of initialization scripts.

2022-07-05 08:06 UTC, rozhkovdmitrii commented on proxy/common_neon/environment_utils.py
> +            logger.error(f"Failed to read sol_account: {name}, that is not a file")
Got rid of it

2022-07-05 13:15 UTC, afalaleev approved these changes

2022-07-05 13:16 UTC, merged