Cancel failed transaction #82
neonevm/proxy-model.py pull request #84
Opened 2021-05-26 22:02 UTC by otselnik

2021-05-27 05:20 UTC, s-medvedev requested changes

2021-05-27 05:20 UTC, s-medvedev commented on proxy/plugin/solana_rest_api_tools.py
> +def send_measured_transaction(client, trx, acc, noexept = False):
It's too complex. Why don't you use exception handling? So you can use `send_measured_transaction` unchanged and all logic will be in `call_signed` like this:
```
def call_signed(...):
   # do some initialization
   # send transaction (we don't need restore action if it fails)
   try:
      result = sol_instr_10_continue(...)
   except Exception as err:
      # save error in log
      sol_instr_12_cancel(...)   # may be it's need to catch exception from `cancel`...
      raise    # reraise actual exception
```

2021-05-27 10:14 UTC, otselnik commented on proxy/plugin/solana_rest_api_tools.py
> +def send_measured_transaction(client, trx, acc, noexept = False):
Agree. I think it belongs to continue function and should be done inside of it.

2021-05-28 04:45 UTC, s-medvedev commented on proxy/plugin/solana_rest_api_tools.py
> +        return result
Why do you raise exception here? It's enough to reriase it in line 355.

2021-05-28 09:57 UTC, s-medvedev approved these changes

2021-05-28 09:57 UTC, merged