#846 resize resource accounts
neonevm/proxy-model.py pull request #852
Opened 2022-07-26 13:35 UTC by otselnik

2022-07-28 09:50 UTC, rozhkovdmitrii commented
No description in related Issue

2022-07-28 10:04 UTC, otselnik commented
> @otselnik, No description in related Issue

Added description.

2022-07-28 11:04 UTC, rozhkovdmitrii requested changes

2022-07-28 11:04 UTC, rozhkovdmitrii commented on proxy/common_neon/neon_instruction.py
> +    def create_refund_instruction(self, account, seed: bytes) -> TransactionInstruction:
1. account - what account? neon signer account?
2. `def create_refund_instruction(self, account: PublicKey, seed: bytes) -> TransactionInstruction:` - annotation missed

2022-07-28 11:04 UTC, rozhkovdmitrii commented on proxy/common_neon/neon_instruction.py
> +            data=bytearray.fromhex("10") + seed,
Isn't it a time to create `Enum` derived class with sensible values. E.g. 
` data=bytearray.fromhex(EvmInstruction.CreateRefund.value) + seed`

2022-07-28 11:04 UTC, rozhkovdmitrii commented on proxy/neon_rpc_api_model/operator_resource_list.py
> +class NeonDeletePermAccountStage(NeonCreatePermAccount):
Shouldn't it be in `neon_tx_stages.py`

2022-07-28 11:04 UTC, rozhkovdmitrii commented on proxy/neon_rpc_api_model/operator_resource_list.py
> +                    tx_refund = TransactionWithComputeBudget()
is it obligatory to create one more transaction? Can it be or should it be processed inside the tx?

2022-07-28 11:04 UTC, rozhkovdmitrii commented on proxy/neon_rpc_api_model/operator_resource_list.py
> +                if account:
I understand it works, but can you please move this case just for one level up to avoid noodle code. And it also would be great if you stuff all the creating end refund processing in a separate method. Then it could looks like that


```python
if _check_refund_or_create_acc(account ...)
```

2022-07-28 11:04 UTC, rozhkovdmitrii commented on proxy/neon_rpc_api_model/operator_resource_list.py
> +                    SolTxListSender(self._s, [tx_refund], refund_stage.NAME).send(self._resource.signer)
```
            elif idx != 0:
                continue
```
Why only for the first account?

2022-07-28 11:04 UTC, rozhkovdmitrii commented on proxy/neon_rpc_api_model/operator_resource_list.py
> +                    SolTxListSender(self._s, [tx_refund], refund_stage.NAME).send(self._resource.signer)
```
            elif account.lamports < balance:
                raise RuntimeError(f"insufficient balance of {str(stage.sol_account)}")
```

Doesn't it got obsolete

2022-07-28 11:04 UTC, rozhkovdmitrii commented on proxy/neon_rpc_api_model/operator_resource_list.py
> +                    SolTxListSender(self._s, [tx_refund], refund_stage.NAME).send(self._resource.signer)
```
                raise RuntimeError(f"wrong owner for: {str(stage.sol_account)}")
```
Why don't you just make an error debug, and miss the loop passage

2022-07-28 11:16 UTC, rozhkovdmitrii commented on proxy/neon_rpc_api_model/operator_resource_list.py
>                  self.debug(f"Create new accounts for resource {resource}")
`self.debug(f"Create new accounts for resource: {resource}")`

2022-08-07 19:58 UTC, afalaleev requested changes

2022-08-07 19:58 UTC, afalaleev commented on proxy/neon_rpc_api_model/operator_resource_list.py
> +    def _make_refund_tx(self, builder, resource, refund_tx, refund_name_list, idx, stage):
Define types of parameters.

2022-08-07 19:58 UTC, afalaleev commented on proxy/neon_rpc_api_model/operator_resource_list.py
> +    def _make_create_acc_tx(self, resource, create_acc_tx, create_acc_tx_name_list, balance, idx, stage):
Define types of parameters

2022-08-08 06:06 UTC, otselnik commented on proxy/common_neon/neon_instruction.py
> +            data=bytearray.fromhex("10") + seed,
Really good idea. Lets do it in other PR.

2022-08-08 06:17 UTC, otselnik commented on proxy/common_neon/neon_instruction.py
> +    def create_refund_instruction(self, account, seed: bytes) -> TransactionInstruction:
fixed

2022-08-08 06:18 UTC, otselnik commented on proxy/neon_rpc_api_model/operator_resource_list.py
> +class NeonDeletePermAccountStage(NeonCreatePermAccount):
fixed

2022-08-08 06:18 UTC, otselnik commented on proxy/neon_rpc_api_model/operator_resource_list.py
> +                    tx_refund = TransactionWithComputeBudget()
moved to tx list

2022-08-08 06:19 UTC, otselnik commented on proxy/neon_rpc_api_model/operator_resource_list.py
> +                if account:
Simplified logic. Fixed

2022-08-08 06:23 UTC, otselnik commented on proxy/neon_rpc_api_model/operator_resource_list.py
> +                    SolTxListSender(self._s, [tx_refund], refund_stage.NAME).send(self._resource.signer)
`idx != 0`: 0 - storage, 1 - holder. Only storage need to be checked for emptiness
`account.lamports < balance`: fixed
`raise RuntimeError(f"wrong owner`: this error should stop execution/ debug is not enough

2022-08-08 06:23 UTC, otselnik commented on proxy/neon_rpc_api_model/operator_resource_list.py
>                  self.debug(f"Create new accounts for resource {resource}")
fixed

2022-08-08 06:23 UTC, otselnik commented on proxy/neon_rpc_api_model/operator_resource_list.py
> +    def _make_refund_tx(self, builder, resource, refund_tx, refund_name_list, idx, stage):
fixed

2022-08-08 06:23 UTC, otselnik commented on proxy/neon_rpc_api_model/operator_resource_list.py
> +    def _make_create_acc_tx(self, resource, create_acc_tx, create_acc_tx_name_list, balance, idx, stage):
fixed

2022-08-08 08:21 UTC, afalaleev approved these changes

2022-08-08 15:11 UTC, afalaleev approved these changes

2022-08-09 06:07 UTC, afalaleev requested changes

2022-08-09 06:07 UTC, afalaleev commented on proxy/common_neon/environment_data.py
> +STORAGE_SIZE = int(os.environ.get("STORAGE_SIZE", "131072")) # 128*1024
As I remember, this size is too small for Midas.
Please increase it.

2022-08-09 09:43 UTC, otselnik commented on proxy/common_neon/environment_data.py
> +STORAGE_SIZE = int(os.environ.get("STORAGE_SIZE", "131072")) # 128*1024
Midas have deployed on devnet and didn't faced this problem.
Maybe some changes on evm decreased storage usage

2022-08-12 11:21 UTC, afalaleev submitted a review, later dismissed

2022-08-15 06:13 UTC, afalaleev requested changes

2022-08-15 06:13 UTC, afalaleev commented on proxy/mempool/operator_resource_list.py
> +                self._make_create_acc_tx(resource, result_stage_list, balance, idx, stage)
If combine these two txs into one tx with two ixs, the source code will become simple.

2022-08-15 06:17 UTC, otselnik commented on proxy/mempool/operator_resource_list.py
> +                self._make_create_acc_tx(resource, result_stage_list, balance, idx, stage)
It didn't work for me. Create account instruction failed because it looked for it like account existed at moment of execution.

2022-08-15 09:17 UTC, otselnik commented on proxy/mempool/operator_resource_list.py
> +                self._make_create_acc_tx(resource, result_stage_list, balance, idx, stage)
Tested it right now. 
Transaction executes successfully, but following tx fails with error:
```
got error: 
Program log: Instruction: Write To Holder. 
Program log: program/src/account/mod.rs:267 : Account BKLT27mXenjyeoKc7Fn8xkrezrNubuRdzbq19mmxW9vS - expected program owned:   File "/opt/proxy/mempool/mempool_executor.py", line 57, in execute_neon_tx
```

2022-08-15 20:30 UTC, rozhkovdmitrii approved these changes, later dismissed

2022-08-15 20:30 UTC, rozhkovdmitrii commented on proxy/mempool/neon_tx_stages.py
> +class NeonCreatePermAccount(NeonCreateAccountWithSeedStage):
Stage

2022-08-15 20:30 UTC, rozhkovdmitrii commented on proxy/neon_rpc_api_model/operator_resource_list.py
> +                    SolTxListSender(self._s, [tx_refund], refund_stage.NAME).send(self._resource.signer)
If you don't use Enum at least make a comment

2022-08-15 20:30 UTC, rozhkovdmitrii commented on proxy/mempool/operator_resource_list.py
> +    def _make_refund_tx(
1. Too many lines
```python
    def _make_refund_tx(self, builder: NeonIxBuilder, resource: OperatorResourceInfo, 
                        refund_stage_list: List[NeonTxStage], idx: int, stage: NeonCreatePermAccount):
```
2. It's up to you, I would list arguments in order what, where. That's why I would place refund_stage_list in last position

2022-08-16 08:41 UTC, otselnik commented on proxy/mempool/neon_tx_stages.py
> +class NeonCreatePermAccount(NeonCreateAccountWithSeedStage):
c

2022-08-16 18:22 UTC, afalaleev approved these changes

2022-08-16 18:28 UTC, merged