#NDEV-399 extract writting holder account
neonevm/proxy-model.py pull request #856
Opened 2022-07-28 08:41 UTC by rozhkovdmitrii

2022-07-28 14:09 UTC, afalaleev requested changes

2022-07-28 14:09 UTC, afalaleev commented on proxy/mempool/transaction_sender.py
> +                strategy = Strategy(self, neon_tx_exec_cfg, self._ctx)
As I see that the `IStrategyUser` is used only in the `execute()` method.
And there are no reasons to pass `IStrategyUser` to ctor of a Strategy to keep an additional reference in the Strategy.

2022-07-28 14:09 UTC, afalaleev commented on proxy/mempool/transaction_sender.py
> +        return self._user.update_tx_accounts_data(neon_tx, accounts_data)
This change doesn't resolve the issue.

2022-07-28 14:09 UTC, afalaleev commented on proxy/common_neon/data.py
> +    accounts_data: Optional[NeonAccountsData] = None
Why do they became an optional parameters?
You didn't prepare other parts of the source code to make parameters optional.

2022-07-28 14:09 UTC, afalaleev commented on proxy/mempool/mempool_executor.py
> +            accounts_data.update({k: emulating_result[k]})
For what purposes you make method on the top of hierarchy?
It isn't used in this part of the source code. And I don't see any reasons for such long hierarchy for this call.

2022-07-28 14:09 UTC, afalaleev commented on proxy/mempool/transaction_sender.py
> +class IStrategyUser(abc.ABC):
What means `StrategyUser`? Why it is `Strategy` ? when it doesn't have any strategy method, and why it is `User` - more strange name for the interface what regenerate the account list.

2022-07-28 14:09 UTC, afalaleev commented on proxy/mempool/transaction_sender.py
> +        return self._user.update_tx_accounts_data(neon_tx, accounts_data)
Why there is no re-running of AccountTxListBuilder and changing of account in NeonIxBuilder?

2022-07-28 15:28 UTC, rozhkovdmitrii commented on proxy/mempool/transaction_sender.py
> +        return self._user.update_tx_accounts_data(neon_tx, accounts_data)
Thank you, for now the changing is inside the `BaseNeonTxStrategy._build_prep_tx_list`

2022-07-28 15:32 UTC, rozhkovdmitrii commented on proxy/common_neon/data.py
> +    accounts_data: Optional[NeonAccountsData] = None
It's only for `test_mempool.py`, there is used a default `MPRequest` with default empty `NeonTxCfg`

2022-07-28 15:37 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_executor.py
> +            accounts_data.update({k: emulating_result[k]})
Because the only this part of hierarchy should know about emulating

2022-07-28 15:39 UTC, rozhkovdmitrii commented on proxy/mempool/transaction_sender.py
> +                strategy = Strategy(self, neon_tx_exec_cfg, self._ctx)
I have a lot to tell about a user interface concept and why it's better then dragging the one-purpose interfaces through the stack, let me please do it in person

2022-07-29 15:29 UTC, afalaleev requested changes
These changes don't work.
You haven't took into account that ATL should wait 1 block till start using, so you should run emulate for ALT strategy after writing into the holder, and writing accounts into ALT.

And with the deep loop of hierarchy call and the hardcoded scenario of integration of holder writting and account creation builder makes a source code more complicated.

2022-08-07 16:55 UTC, rozhkovdmitrii commented
obsolete

2022-08-07 16:55 UTC, closed without merging