NDEV-496 Create method neon_getEvmParams
neonevm/proxy-model.py pull request #861
Opened 2022-08-05 13:06 UTC by ivandzen

2022-08-05 13:55 UTC, afalaleev requested changes

2022-08-05 13:55 UTC, afalaleev commented on proxy/neon_rpc_api_model/neon_rpc_api_model.py
> +    def neon_getEvmParams(self, param_name):
Why the name of the method is `neon_getEvParamS`, but it returns a param by name?

2022-08-05 13:55 UTC, afalaleev commented on proxy/neon_rpc_api_model/neon_rpc_api_model.py
> +    def neon_getEvmParams(self, param_name):
I suggested that the method should return the entire parameter map, and the parameter should be easy to get by name on the client side.

2022-08-05 13:55 UTC, afalaleev commented on proxy/neon_rpc_api_model/neon_rpc_api_model.py
> +    def neon_getEvmParams(self, param_name):
Please, define the return type: `def neon_getEvmParams(self) -> Dict[str, Any]:`

2022-08-05 14:16 UTC, ivandzen commented on proxy/neon_rpc_api_model/neon_rpc_api_model.py
> +    def neon_getEvmParams(self, param_name):
Fixed

2022-08-06 03:38 UTC, rozhkovdmitrii commented on proxy/testing/test_get_evm_params.py
> +from ..common_neon.elf_params import ElfParams
not used

2022-08-06 03:38 UTC, rozhkovdmitrii commented on proxy/testing/test_get_evm_params.py
> +        print(f'Neon-EVM Params: {proxy.neon.getEvmParams()}')
Don't forget please to update documentation

2022-08-06 03:38 UTC, rozhkovdmitrii commented on proxy/neon_rpc_api_model/neon_rpc_api_model.py
> +        """
If takes single line let it be a single line

2022-08-06 03:38 UTC, rozhkovdmitrii commented on proxy/common_neon/web3.py
> +
two blank lines

2022-08-07 15:40 UTC, afalaleev approved these changes, later dismissed

2022-08-08 05:06 UTC, ivandzen commented on proxy/common_neon/web3.py
> +
done

2022-08-08 05:07 UTC, ivandzen commented on proxy/neon_rpc_api_model/neon_rpc_api_model.py
> +        """
done

2022-08-08 05:07 UTC, ivandzen commented on proxy/testing/test_get_evm_params.py
> +        print(f'Neon-EVM Params: {proxy.neon.getEvmParams()}')
Will do

2022-08-08 05:07 UTC, ivandzen commented on proxy/testing/test_get_evm_params.py
> +from ..common_neon.elf_params import ElfParams
removed

2022-08-08 05:54 UTC, rozhkovdmitrii approved these changes

2022-08-08 05:54 UTC, rozhkovdmitrii approved these changes, later dismissed

2022-08-08 08:46 UTC, rozhkovdmitrii approved these changes

2022-08-08 08:47 UTC, merged