Ndev 419 make operator resource list a part of the mem pool
neonevm/proxy-model.py pull request #869
Opened 2022-08-08 13:53 UTC by otselnik

2022-08-15 04:24 UTC, afalaleev requested changes

2022-08-15 04:24 UTC, afalaleev commented on proxy/mempool/mempool_api.py
> +        hash = "0x" + self.neon_tx.hash_signed().hex()
What is the reason for this change?
Is there any other place in the source code where the transaction is initialized except memclient::send_raw_transaction?

2022-08-15 04:24 UTC, afalaleev commented on proxy/mempool/mempool_api.py
> +    PendingTxError = 3,
A pending error was removed from the source code.

2022-08-15 04:24 UTC, afalaleev commented on proxy/mempool/operator_resource_list.py
> +    def _create_ether_account(self, builder: NeonIxBuilder, resource: OperatorResourceInfo) -> EthereumAddress:
The function returns List of Stages, not Ethereum address

2022-08-15 09:29 UTC, otselnik commented on proxy/mempool/mempool_api.py
> +    PendingTxError = 3,
Removed

2022-08-15 09:29 UTC, otselnik commented on proxy/mempool/operator_resource_list.py
> +    def _create_ether_account(self, builder: NeonIxBuilder, resource: OperatorResourceInfo) -> EthereumAddress:
Fixed

2022-08-15 09:30 UTC, otselnik commented on proxy/mempool/mempool_api.py
> +        hash = "0x" + self.neon_tx.hash_signed().hex()
Looks like merge artifact - reverted changes.

2022-08-17 10:46 UTC, rozhkovdmitrii requested changes

2022-08-17 10:46 UTC, rozhkovdmitrii commented on proxy/mempool/mempool.py
> +        self._check_resources_task = asyncio.get_event_loop().create_task(self.check_resources_schedule())
Why is it a part of mempool? All the operator management logic should be encapsulated

2022-08-17 10:46 UTC, rozhkovdmitrii commented on proxy/mempool/operator_resource_list.py
> +    _free_resource_list = list()
Move it please into `__init__`

2022-08-17 10:46 UTC, rozhkovdmitrii commented on proxy/mempool/operator_resource_list.py
Double blank line

2022-08-17 10:46 UTC, rozhkovdmitrii commented on proxy/mempool/mempool.py
> +                self._update_locked_resource(mp_request)
Isn't it a part of blocked account processing? Why haven't you hidden it behind the `_on_blocked_accounts_result`

2022-08-17 10:46 UTC, rozhkovdmitrii commented on proxy/mempool/operator_resource_list.py
> +        if self._allocated_resource.get(tx_hash) is not None:
```python
resource_idx = self._allocated_resource.get(tx_hash)
if resource_ids is not None:
    resource = self._resource_list[resource_idx]
```

2022-08-17 10:46 UTC, rozhkovdmitrii commented on proxy/mempool/operator_resource_list.py
> +            resource = self._resource_list[idx]
`return resource`?

2022-08-17 10:46 UTC, rozhkovdmitrii commented on proxy/mempool/operator_resource_list.py
> +from typing import Dict, Optional, List
```python
from ..common_neon.environment_data import EVM_LOADER_ID, PERM_ACCOUNT_LIMIT, RECHECK_RESOURCE_LIST_INTERVAL
from ..common_neon.environment_data import MIN_OPERATOR_BALANCE_TO_WARN, MIN_OPERATOR_BALANCE_TO_ERR, STORAGE_SIZE
```
is it possible to get these configuration through the Config?

2022-08-17 10:46 UTC, rozhkovdmitrii commented on proxy/mempool/operator_resource_list.py
> +    _free_resource_list = list()
It should be annotated

2022-08-17 10:46 UTC, rozhkovdmitrii commented on proxy/mempool/mempool.py
> +    async def check_resources_schedule(self):
It should be hidden behind the OperatorResourceMng

2022-08-17 10:46 UTC, rozhkovdmitrii commented on proxy/mempool/operator_resource_list.py
> +            for blocked_tx_hash, access_time in self._allocated_resource_access:
We can't check resource liquidity only through the  `BadResource` error. 
In this case we use the same resource periodically, each time face the same error, each time send resource to the future.

There is another thing you should know, the set of resources can be changed on the fly and operator resource list should be able to solve all the changes.

2022-08-17 10:46 UTC, rozhkovdmitrii commented on proxy/mempool/operator_resource_list.py
> +    def recheck_resource_list_interval() -> int:
will gone if you encapsulate all the operator resource management here

2022-08-17 10:46 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_executor.py
> +from proxy.common_neon.errors import BadResourceError
relative path

2022-08-17 10:46 UTC, rozhkovdmitrii commented on proxy/mempool/mempool.py
> +        self._resource_mng = OperatorResourceManager()
If you encapsulate all the operator management stuff in `OperatorResourceManager` you will have to pass it here by interface to be able test MemPool independently

2022-08-17 10:46 UTC, rozhkovdmitrii commented on proxy/mempool/mempool.py
> +        self._check_resources_task = asyncio.get_event_loop().create_task(self.check_resources_schedule())
Shouldn't be here

2022-08-17 10:46 UTC, rozhkovdmitrii commented on proxy/mempool/mempool.py
> +                        asyncio.get_event_loop().create_task(self._reschedule_tx(mp_request))
do not acquire transaction if you don't  have a resource. Change the order please

2022-08-17 10:46 UTC, rozhkovdmitrii commented on proxy/mempool/mempool.py
> +                self._update_locked_resource(mp_request)
If it's a part of blocked account result processing it should be encapsulated there

2022-08-17 10:46 UTC, rozhkovdmitrii commented on proxy/mempool/mempool.py
> +                self._bad_resource(mp_request)
If it's a part of bad resource result processing it should be encapsulated there. Here should stay only on call

2022-08-17 10:53 UTC, otselnik commented on proxy/mempool/mempool.py
> +                        asyncio.get_event_loop().create_task(self._reschedule_tx(mp_request))
To be abble to get same resource for a transaction it need to be acquired first

2022-08-17 10:56 UTC, rozhkovdmitrii commented on proxy/common_neon/errors.py
> +    def __int__(self):
pass

2022-08-17 10:56 UTC, rozhkovdmitrii commented on proxy/mempool/mempool.py
> +                        asyncio.get_event_loop().create_task(self._reschedule_tx(mp_request))
May be the better way then is to seek for transaction and then, after getting resource, acquire it

2022-08-17 10:59 UTC, rozhkovdmitrii commented
OperatorResourceManager should certainly be covered with unittests

2022-08-18 10:18 UTC, otselnik commented on proxy/common_neon/errors.py
> +    def __int__(self):
Left it for similarity.

2022-08-18 10:18 UTC, otselnik commented on proxy/mempool/mempool.py
> +        self._resource_mng = OperatorResourceManager()
I think there is no need to hide `OperatorResourceManager` behind interface. It does not interact with anything besides solana accounts on fs.

2022-08-18 10:18 UTC, otselnik commented on proxy/mempool/mempool.py
> +        self._check_resources_task = asyncio.get_event_loop().create_task(self.check_resources_schedule())
Moved to `OperatorResourceManager`

2022-08-18 10:18 UTC, otselnik commented on proxy/mempool/mempool.py
> +                        asyncio.get_event_loop().create_task(self._reschedule_tx(mp_request))
Implemented

2022-08-18 10:18 UTC, otselnik commented on proxy/mempool/mempool.py
> +                self._update_locked_resource(mp_request)
Fixed.

2022-08-18 10:18 UTC, otselnik commented on proxy/mempool/mempool.py
> +                self._update_locked_resource(mp_request)
Fixed.

2022-08-18 10:18 UTC, otselnik commented on proxy/mempool/mempool.py
> +                self._bad_resource(mp_request)
Fixed.

2022-08-18 10:18 UTC, otselnik commented on proxy/mempool/mempool.py
> +    async def check_resources_schedule(self):
Fixed.

2022-08-18 10:18 UTC, otselnik commented on proxy/mempool/mempool_executor.py
> +from proxy.common_neon.errors import BadResourceError
Fixed.

2022-08-18 10:18 UTC, otselnik commented on proxy/mempool/operator_resource_list.py
> +from typing import Dict, Optional, List
Moved

2022-08-18 10:18 UTC, otselnik commented on proxy/mempool/operator_resource_list.py
As it should be?

2022-08-18 10:18 UTC, otselnik commented on proxy/mempool/operator_resource_list.py
> +    _free_resource_list = list()
Done

2022-08-18 10:18 UTC, otselnik commented on proxy/mempool/operator_resource_list.py
> +    _free_resource_list = list()
Done

2022-08-18 10:18 UTC, otselnik commented on proxy/mempool/operator_resource_list.py
> +        if self._allocated_resource.get(tx_hash) is not None:
Done

2022-08-18 10:18 UTC, otselnik commented on proxy/mempool/operator_resource_list.py
> +            resource = self._resource_list[idx]
Fixed

2022-08-18 10:46 UTC, otselnik commented on proxy/common_neon/config.py
> +        return SOLANA_URL
I changed parameters acquiring. Default values should be defined in one place.

2022-08-22 14:20 UTC, rozhkovdmitrii commented on proxy/common_neon/config.py
> +        return SOLANA_URL
ok

2022-08-22 14:38 UTC, rozhkovdmitrii commented on proxy/mempool/mempool.py
> +        self._check_resources_task = asyncio.get_event_loop().create_task(self.check_resources_schedule())
```python
        self._resource_mng.start_periodical_checker()
```

I'm sorry about it, but it's not been. You can safely start it from OperatorResourceManager constructor. There is no need to get MemPool known about anything inside the OperatorResourceManager excluding getting and releasing resource

2022-08-22 14:52 UTC, rozhkovdmitrii commented on proxy/mempool/operator_resource_list.py
> +        if self._allocated_resource.get(tx_hash) is not None:
done

2022-08-22 14:56 UTC, rozhkovdmitrii commented on proxy/mempool/operator_resource_list.py
> +            for blocked_tx_hash, access_time in self._allocated_resource_access:
@otselnik

2022-08-22 15:01 UTC, rozhkovdmitrii commented on proxy/mempool/operator_resource_list.py
Yep, these are top level definitions

2022-08-22 15:04 UTC, rozhkovdmitrii commented on proxy/mempool/mempool.py
> +        self._resource_mng = OperatorResourceManager()
If you do it like that you will be able to test MemPool more independently and moreover will be prevented from calling stuff that is not a part of interface like `start_periodical_checker`

2022-08-22 15:07 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_executor.py
> +from proxy.common_neon.errors import BadResourceError
I don't understand why don't you use single line import for these two lines

2022-08-22 15:21 UTC, rozhkovdmitrii commented on proxy/common_neon/errors.py
> +    def __int__(self):
I understand it's not critical and I won't pick on it.
But if you do not pass any arguments in it, it's better to use pass to keep it

2022-08-22 18:56 UTC, rozhkovdmitrii commented on proxy/common_neon/config.py
>  import os
got redundant

2022-08-22 18:56 UTC, rozhkovdmitrii commented on proxy/common_neon/config.py
> +        return RECHECK_RESOURCE_LIST_INTERVAL
Extend `__str__` with it please

2022-08-22 18:56 UTC, rozhkovdmitrii commented on proxy/mempool/operator_resource_list.py
> +            elif account.owner != PublicKey(self._config.get_evm_loader_id()):
`self._config.get_evm_loader_id()` - returns public key

2022-08-22 18:56 UTC, rozhkovdmitrii commented on proxy/mempool/operator_resource_list.py
> +    def _recheck_bad_resource_list(self) -> int:
It doesn't return `int`

2022-08-22 18:56 UTC, rozhkovdmitrii commented on proxy/mempool/operator_resource_list.py
> +    def fill_storage_holder(self):
The only responsibility of this structure is - to be transferred to the mp executor and be fed to neon transaction processing. I would be better if you left it inside OperatorResourceManager. Please do it

2022-08-22 18:56 UTC, rozhkovdmitrii commented on proxy/mempool/mempool.py
> +                    tx_hash = self._tx_schedule.get_tx_good_for_execution()
peek_tx_for_execution

2022-08-22 18:56 UTC, rozhkovdmitrii commented on proxy/mempool/mempool.py
> +        self._resource_mng.start_periodical_checker()
can be isolated inside the manager

2022-08-22 18:56 UTC, rozhkovdmitrii commented on proxy/mempool/operator_resource_list.py
> +    def deallocate_resource(self, tx_hash: str, resource: OperatorResourceInfo) -> None:
1. release_resource
2. why do you use resource parameter, all the needed information is already inside. It looks like if you get rid of it, the logic will straighten up

2022-08-22 18:56 UTC, rozhkovdmitrii commented on proxy/mempool/mempool.py
> +        self._update_locked_resource(mp_tx_request)
it's workaround should gone in the next PR as we got agreed

2022-08-22 18:56 UTC, rozhkovdmitrii commented on proxy/mempool/mempool.py
> +        self._bad_resource(mp_tx_request)
We already are inside "bad resource" handler )

2022-08-22 18:56 UTC, rozhkovdmitrii commented on proxy/mempool/mempool.py
> +    def _on_bad_resource_error_result(self, mp_tx_request: MPTxRequest, mp_tx_result: MPTxResult):
`on_bad_resource_result`

2022-08-22 18:56 UTC, rozhkovdmitrii commented on proxy/mempool/mempool.py
> +        asyncio.get_event_loop().create_task(self._reschedule_tx(mp_tx_request))
It seems logging and rescheduling is a separate thing.
The first action to be logged is the "bad resource" result

The second is rescheduling (with logging), now it seems is able to be extracted

2022-08-22 18:56 UTC, rozhkovdmitrii commented on proxy/mempool/mempool.py
> +        self._free_resource(mp_tx_request)
`release_resource(mp_tx_request.hash)`

2022-08-22 18:56 UTC, rozhkovdmitrii commented on proxy/mempool/mempool.py
> +        self._update_locked_resource(mp_tx_request)
it's workaround should gone in the next PR as we got agreed

2022-08-22 18:56 UTC, rozhkovdmitrii commented on proxy/mempool/mempool.py
> +        mp_tx_request.resource = None
It's certainly shouldn't be here
It looks like an "ill sign"
Resource shouldn't be a part of request, it should be passed aside of it as it is or as a part of "processing context", we discussed it earlier
All the information you need is the transaction hash to release and get resource

2022-08-22 18:56 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_executor.py
> +        if not ResourceInitializer(self._config, self._solana_interactor).init_resource(mp_tx_request.resource):
Don't understand should it be inside the OperatorResourceManager processing or not

2022-08-22 18:56 UTC, rozhkovdmitrii commented on proxy/mempool/mempool.py
> +        self._resource_mng.update_allocated_resource(mp_tx_request.signature, mp_tx_request.resource)
self._resource_mng.update_allocated_resource(mp_tx_request.signature~~, mp_tx_request.resource~~)

2022-08-22 18:56 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_executor.py
>      def execute_neon_tx_impl(self, mp_tx_request: MPTxRequest):
`def execute_neon_tx_impl(self, mp_tx_request: MPTxRequest, mp_exec_ctx: MPExecCtx):` 

resource is a context like an emulating result derivatives, please do not  stuff all things into `MPTxRequest`. 
MpTxRequest is not good and it's my fault, please don't make it worse

2022-08-22 18:56 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_schedule.py
> +        return self.get_tx()
`self.peek_tx()`

2022-08-22 18:56 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_schedule.py
> +    def get_tx_good_for_execution(self) -> Optional[str]:
Here are two methods get_tx_good_for_processing and this one )))

2022-08-23 18:43 UTC, rozhkovdmitrii commented on proxy/common_neon/errors.py
> +    def __int__(self):
done

2022-08-23 22:13 UTC, rozhkovdmitrii commented on proxy/mempool/mempool.py
> +        self._resource_mng.update_allocated_resource(mp_tx_request.signature, mp_tx_request.resource)
done

2022-08-23 22:14 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_executor.py
>      def execute_neon_tx_impl(self, mp_tx_request: MPTxRequest):
done in a little bit different way

2022-08-24 00:06 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_executor.py
> +        if not ResourceInitializer(self._config, self._solana_interactor).init_resource(mp_tx_request.resource):
Agree it's a task related to bringing checking balances and keys on the separate process

2022-08-24 00:39 UTC, rozhkovdmitrii approved these changes

2022-08-24 07:10 UTC, afalaleev approved these changes

2022-08-24 07:19 UTC, merged