Ndev 420 reschedule neon transaction with the same resource
neonevm/proxy-model.py pull request #871
Opened 2022-08-10 12:11 UTC by otselnik

2022-08-11 09:18 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_api.py
> +    resource: OperatorResourceInfo = field(compare=False, default=None)
Is it should be here?

2022-08-11 09:19 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_api.py
> +from proxy.mempool.operator_resource_mng import OperatorResourceInfo
relative path

2022-08-11 09:44 UTC, rozhkovdmitrii commented on proxy/mempool/operator_resource_mng.py
> +    def init_perm_accounts(self, solana: SolanaInteractor) -> bool:
Move it into OperatorResourceMng please

2022-08-11 09:49 UTC, rozhkovdmitrii commented on proxy/mempool/operator_resource_mng.py
> +from ..common_neon.environment_data import EVM_LOADER_ID, PERM_ACCOUNT_LIMIT, RECHECK_RESOURCE_LIST_INTERVAL
In the mempool we use Config class to get things like this one

2022-08-11 12:46 UTC, otselnik commented on proxy/mempool/mempool_api.py
> +    resource: OperatorResourceInfo = field(compare=False, default=None)
IMO - yes

2022-08-11 12:47 UTC, otselnik commented on proxy/mempool/mempool_api.py
> +from proxy.mempool.operator_resource_mng import OperatorResourceInfo
fixed in [NDEV-419](https://github.com/neonlabsorg/proxy-model.py/pull/869) PR

2022-08-11 12:47 UTC, otselnik commented on proxy/mempool/operator_resource_mng.py
> +    def init_perm_accounts(self, solana: SolanaInteractor) -> bool:
Need to be discused

2022-08-15 04:28 UTC, afalaleev requested changes

2022-08-15 04:28 UTC, afalaleev commented on proxy/mempool/mempool_schedule.py
> +        index = bisect.bisect_left(self._txs, mp_tx_request)
It is impossible to execute another transaction except the first in the queue. 
So there are no reasons to find the transaction in the queue, all previous checks are correct.
And this check is surplus.

2022-08-15 06:06 UTC, otselnik commented
Changes implemented in
https://github.com/neonlabsorg/proxy-model.py/pull/869

2022-08-15 06:06 UTC, closed without merging