Ndev 521 mempool replication
neonevm/proxy-model.py pull request #884
Opened 2022-08-24 13:10 UTC by rozhkovdmitrii

2022-08-26 18:37 UTC, afalaleev approved these changes, later dismissed

2022-08-29 13:36 UTC, afalaleev requested changes
I'm sorry, I can return to the PR later to provide information how to resolve issues.
Currently it has a lot of problems.

2022-08-29 13:36 UTC, afalaleev commented on proxy/mempool/mempool_service.py
> +        self.error(f"Failed to process mp_reqeust, unknown type: {mp_request.type}")
Typo: mp_reqeust -> mp_request

2022-08-29 13:36 UTC, afalaleev commented on proxy/mempool/mempool_api.py
> +from typing import Any, Optional, List, Tuple
Tuple is not used

2022-08-29 13:36 UTC, afalaleev commented on proxy/mempool/mempool_schedule.py
> +            sorted_queue = SortedQueue[SortedQueueItem, int, str](lt_key_func=lambda a: -a.nonce,eq_key_func=lambda a: a.signature)
Sorted queue is used not only for nonce-queue.

1. If you want to define type - `SortedQueue[SortedQueueItem, SortedQueueLtKey, SortedQueueEqKey](lt_key_func=self._impl._lt_key_func, eq_key_func=self._eq_key_func)`
2. Return type of function is wrong.

2022-08-29 13:36 UTC, afalaleev commented on proxy/mempool/mempool_schedule.py
> +        return len(self._tx_nonce_queue)
For what? You already have `get_queue_len()`

2022-08-29 13:36 UTC, afalaleev commented on proxy/mempool/mempool_service.py
> +            self.error(f"Failed to process maintenance request: {mp_request.command}, {err}, traceback: {err_tb}", extra=log_ctx)
```
with logging_context(req_id=mp_request.req_id):
    self._on_exception(f"Failed to process maintenance request: {mp_request.command}", err)
```

2022-08-29 13:36 UTC, afalaleev commented on proxy/mempool/mempool_service.py
> +        self._mempool.on_operator_resource_released()
This event is absent.

2022-08-29 13:36 UTC, afalaleev commented on proxy/mempool/mempool_schedule.py
> +        for tx_pool in self._sender_pool_queue:
`self._sender_pool_queue` has only senders that are ready to be executed.
The full list of senders is in the `self._sender_pool_dict`.

2022-08-29 13:36 UTC, afalaleev commented on proxy/mempool/mempool_schedule.py
> +        taken_out_txs = self._tx_nonce_queue[_from:]
You need `List[MPTxRequest]`, but you return the `Sorted Queue of the MPTxRequest`...

I understand that you have implemented the traditional python way for lists.

But, If you add the method `take_out_txs` that has a custom implementation for the custom case, it looks better to make it really custom 
- in the sorted queue implement logic that returns the List! (not sorted queue!) of items by dropping them from the internal list of the sorted queue. 
- the implementation will really simple - you make a copy of the `_impl.queue[from:]`, and drop all items in the `_impl.queue`
- don't call pop method for txs inside the `take_out_txs`

Another way - is to keep the structure of MPSenderTxPool simple wo high level logic in it....

2022-08-29 13:36 UTC, afalaleev commented on proxy/mempool/mempool_schedule.py
> +            self._sender_pool_queue.pop(tx_pool)
This place has a lot of problems ....

2022-08-29 13:36 UTC, afalaleev commented on proxy/mempool/mempool_schedule.py
> +            self._sender_pool_queue.pop(tx_pool)
If pool is not in the queue of the execution it raises an exception

2022-08-29 15:02 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_schedule.py
> +            sorted_queue = SortedQueue[SortedQueueItem, int, str](lt_key_func=lambda a: -a.nonce,eq_key_func=lambda a: a.signature)
OMG, of course you are right !

2022-08-29 16:00 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_schedule.py
> +        for tx_pool in self._sender_pool_queue:
It's a crucial thing I've missed thank you

2022-08-29 16:16 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_schedule.py
> +            self._sender_pool_queue.pop(tx_pool)
That is impossible case, Andrew, because I stuff the empty_pools four lines before

2022-08-29 16:20 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_schedule.py
> +            self._sender_pool_queue.pop(tx_pool)
But as you mentioned before not all the pools are in _sender_pool_queue

2022-08-29 18:32 UTC, afalaleev commented on proxy/mempool/mempool_schedule.py
> +            self._sender_pool_queue.pop(tx_pool)
Sender pool has 3 states:
if pool.is_paused() -> paused_sender_set (+),  sender_pool_queue(-)
elif pool.is_processing -> paused_sender_set(-), send_pool_queue(-)
else -> paused_sender_state(-), sender_pool_queue(+)

2022-08-29 19:24 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_service.py
> +        self.error(f"Failed to process mp_reqeust, unknown type: {mp_request.type}")
solved

2022-08-29 19:24 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_api.py
> +from typing import Any, Optional, List, Tuple
solved

2022-08-29 19:24 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_schedule.py
> +            sorted_queue = SortedQueue[SortedQueueItem, int, str](lt_key_func=lambda a: -a.nonce,eq_key_func=lambda a: a.signature)
Reduced with generic parameters

2022-08-29 19:25 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_schedule.py
> +        return len(self._tx_nonce_queue)
Dropped away

2022-08-29 19:26 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_service.py
> +            self.error(f"Failed to process maintenance request: {mp_request.command}, {err}, traceback: {err_tb}", extra=log_ctx)
I'll see what I can do with it in the python-logged-groups in the future issues. Now it's self._on_exception

2022-08-29 19:26 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_service.py
> +        self._mempool.on_operator_resource_released()
Thank you, solved

2022-08-29 19:27 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_schedule.py
> +        for tx_pool in self._sender_pool_queue:
solved, walk through the `_sender_pool_dict`

2022-08-29 19:29 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_schedule.py
> +        taken_out_txs = self._tx_nonce_queue[_from:]
I prefer to not touch Generic Sorted Queue. I made a mess with the return  type and the actual value, thank you for remark

2022-08-29 19:29 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_schedule.py
> +        taken_out_txs = self._tx_nonce_queue[_from:]
solved

2022-08-29 19:29 UTC, rozhkovdmitrii commented on proxy/mempool/mempool_schedule.py
> +            self._sender_pool_queue.pop(tx_pool)
solved

2022-08-29 19:32 UTC, rozhkovdmitrii commented
@afalaleev solved all remarks, do merging develop and tests

2022-08-30 08:31 UTC, afalaleev approved these changes

2022-08-30 08:31 UTC, afalaleev commented on proxy/mempool/mempool_service.py
> +            self.error(f"Failed to process maintenance request: {mp_request.command}, {err}, traceback: {err_tb}", extra=log_ctx)
Ok, lets do it later.

2022-08-30 10:32 UTC, merged