NDEV 501 log gas for each ix
neonevm/proxy-model.py pull request #947
Opened 2022-09-15 13:59 UTC by valiksinev

2022-09-16 08:10 UTC, afalaleev requested changes

2022-09-16 08:10 UTC, afalaleev commented on proxy/common_neon/evm_log_decoder.py
> +        elif data_list[0].startswith('IX_GAS'):
Please move this to here - https://github.com/neonlabsorg/proxy-model.py/blob/develop/proxy/common_neon/solana_neon_tx_receipt.py#L412-L414

2022-09-16 08:43 UTC, valiksinev commented on proxy/common_neon/evm_log_decoder.py
> +        elif data_list[0].startswith('IX_GAS'):
fixed

2022-09-18 19:08 UTC, afalaleev approved these changes

2022-09-20 13:47 UTC, merged